// Bank soal kuis Bahasa Indonesia.
// Format: { q: pertanyaan, a: jawaban benar, w: [3 jawaban salah], c: kategori, d: tingkat kesulitan }

module.exports = [
  // --- Geografi ---
  { q: "Gunung tertinggi di Indonesia adalah?", a: "Puncak Jaya", w: ["Gunung Semeru", "Gunung Kerinci", "Gunung Rinjani"], c: "Geografi", d: "easy" },
  { q: "Danau vulkanik terbesar di Indonesia adalah?", a: "Danau Toba", w: ["Danau Maninjau", "Danau Singkarak", "Danau Sentani"], c: "Geografi", d: "easy" },
  { q: "Candi Borobudur terletak di provinsi?", a: "Jawa Tengah", w: ["DI Yogyakarta", "Jawa Timur", "Jawa Barat"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Provinsi Sumatera Utara?", a: "Medan", w: ["Padang", "Pekanbaru", "Banda Aceh"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Jawa Barat?", a: "Bandung", w: ["Bogor", "Cirebon", "Bekasi"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Sulawesi Selatan?", a: "Makassar", w: ["Manado", "Palu", "Kendari"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Kalimantan Timur?", a: "Samarinda", w: ["Balikpapan", "Banjarmasin", "Pontianak"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Provinsi Bali?", a: "Denpasar", w: ["Singaraja", "Ubud", "Kuta"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Papua?", a: "Jayapura", w: ["Merauke", "Sorong", "Manokwari"], c: "Geografi", d: "medium" },
  { q: "Pulau Komodo terletak di provinsi?", a: "Nusa Tenggara Timur", w: ["Nusa Tenggara Barat", "Bali", "Maluku"], c: "Geografi", d: "medium" },
  { q: "Selat yang memisahkan Pulau Jawa dan Pulau Sumatera adalah?", a: "Selat Sunda", w: ["Selat Malaka", "Selat Bali", "Selat Makassar"], c: "Geografi", d: "easy" },
  { q: "Selat yang memisahkan Pulau Jawa dan Pulau Bali adalah?", a: "Selat Bali", w: ["Selat Lombok", "Selat Sunda", "Selat Madura"], c: "Geografi", d: "easy" },
  { q: "Sungai terpanjang di Indonesia adalah?", a: "Sungai Kapuas", w: ["Sungai Mahakam", "Sungai Musi", "Sungai Barito"], c: "Geografi", d: "medium" },
  { q: "Negara yang berbatasan darat dengan Indonesia di Pulau Papua adalah?", a: "Papua Nugini", w: ["Australia", "Timor Leste", "Filipina"], c: "Geografi", d: "easy" },
  { q: "Samudra terluas di dunia adalah?", a: "Samudra Pasifik", w: ["Samudra Atlantik", "Samudra Hindia", "Samudra Arktik"], c: "Geografi", d: "easy" },
  { q: "Benua terbesar di dunia adalah?", a: "Asia", w: ["Afrika", "Amerika Utara", "Eropa"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Jepang?", a: "Tokyo", w: ["Osaka", "Kyoto", "Hiroshima"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Australia?", a: "Canberra", w: ["Sydney", "Melbourne", "Perth"], c: "Geografi", d: "medium" },
  { q: "Menara Eiffel berada di kota?", a: "Paris", w: ["London", "Roma", "Berlin"], c: "Geografi", d: "easy" },
  { q: "Apa nama mata uang Jepang?", a: "Yen", w: ["Won", "Yuan", "Ringgit"], c: "Geografi", d: "easy" },
  { q: "Apa nama mata uang Malaysia?", a: "Ringgit", w: ["Baht", "Peso", "Dong"], c: "Geografi", d: "easy" },
  { q: "Kota manakah yang dijuluki Kota Kembang?", a: "Bandung", w: ["Bogor", "Malang", "Semarang"], c: "Geografi", d: "easy" },
  { q: "Kota manakah yang dijuluki Kota Pahlawan?", a: "Surabaya", w: ["Jakarta", "Semarang", "Medan"], c: "Geografi", d: "easy" },
  { q: "Kota manakah yang dijuluki Kota Hujan?", a: "Bogor", w: ["Bandung", "Padang", "Manado"], c: "Geografi", d: "easy" },
  { q: "Kota manakah yang dijuluki Kota Pelajar?", a: "Yogyakarta", w: ["Bandung", "Malang", "Surabaya"], c: "Geografi", d: "easy" },

  // --- Sejarah & Kewarganegaraan ---
  { q: "Kapan proklamasi kemerdekaan Indonesia dibacakan?", a: "17 Agustus 1945", w: ["17 Agustus 1944", "1 Juni 1945", "28 Oktober 1928"], c: "Sejarah", d: "easy" },
  { q: "Siapa presiden pertama Republik Indonesia?", a: "Soekarno", w: ["Mohammad Hatta", "Soeharto", "Sutan Sjahrir"], c: "Sejarah", d: "easy" },
  { q: "Siapa wakil presiden pertama Republik Indonesia?", a: "Mohammad Hatta", w: ["Adam Malik", "Sri Sultan Hamengkubuwono IX", "Sutan Sjahrir"], c: "Sejarah", d: "easy" },
  { q: "Siapa presiden ketiga Republik Indonesia?", a: "B.J. Habibie", w: ["Abdurrahman Wahid", "Megawati Soekarnoputri", "Susilo Bambang Yudhoyono"], c: "Sejarah", d: "easy" },
  { q: "Siapa presiden keempat Republik Indonesia?", a: "Abdurrahman Wahid", w: ["B.J. Habibie", "Megawati Soekarnoputri", "Soeharto"], c: "Sejarah", d: "medium" },
  { q: "Sumpah Pemuda diikrarkan pada tahun?", a: "1928", w: ["1908", "1945", "1926"], c: "Sejarah", d: "easy" },
  { q: "Hari Pendidikan Nasional diperingati setiap tanggal?", a: "2 Mei", w: ["20 Mei", "21 April", "10 November"], c: "Sejarah", d: "easy" },
  { q: "Hari Pahlawan diperingati setiap tanggal?", a: "10 November", w: ["17 Agustus", "1 Oktober", "28 Oktober"], c: "Sejarah", d: "easy" },
  { q: "Hari Kartini diperingati setiap tanggal?", a: "21 April", w: ["2 Mei", "22 Desember", "20 Mei"], c: "Sejarah", d: "easy" },
  { q: "Siapa tokoh yang dijuluki Bapak Pendidikan Nasional?", a: "Ki Hajar Dewantara", w: ["Dewi Sartika", "R.A. Kartini", "H.O.S. Tjokroaminoto"], c: "Sejarah", d: "easy" },
  { q: "Siapa pencipta lagu Indonesia Raya?", a: "W.R. Supratman", w: ["Ismail Marzuki", "Cornel Simanjuntak", "Ibu Sud"], c: "Sejarah", d: "easy" },
  { q: "Siapa yang menjahit Bendera Pusaka Merah Putih?", a: "Fatmawati", w: ["R.A. Kartini", "Cut Nyak Dhien", "Dewi Sartika"], c: "Sejarah", d: "easy" },
  { q: "Kerajaan Hindu tertua di Indonesia adalah?", a: "Kutai", w: ["Tarumanegara", "Majapahit", "Sriwijaya"], c: "Sejarah", d: "medium" },
  { q: "Mahapatih Majapahit yang terkenal dengan Sumpah Palapa adalah?", a: "Gajah Mada", w: ["Hayam Wuruk", "Ken Arok", "Raden Wijaya"], c: "Sejarah", d: "easy" },
  { q: "Pahlawan nasional perempuan asal Aceh yang melawan Belanda adalah?", a: "Cut Nyak Dhien", w: ["Martha Christina Tiahahu", "Dewi Sartika", "Nyi Ageng Serang"], c: "Sejarah", d: "easy" },
  { q: "Perang Diponegoro (Perang Jawa) berlangsung pada tahun?", a: "1825–1830", w: ["1811–1816", "1945–1949", "1873–1904"], c: "Sejarah", d: "hard" },
  { q: "Konferensi Asia Afrika tahun 1955 diadakan di kota?", a: "Bandung", w: ["Jakarta", "Bogor", "Yogyakarta"], c: "Sejarah", d: "easy" },
  { q: "ASEAN didirikan pada tahun?", a: "1967", w: ["1955", "1945", "1975"], c: "Sejarah", d: "medium" },
  { q: "Apa semboyan negara Indonesia?", a: "Bhinneka Tunggal Ika", w: ["Tut Wuri Handayani", "Gotong Royong", "Jalesveva Jayamahe"], c: "Kewarganegaraan", d: "easy" },
  { q: "Apa bunyi sila ketiga Pancasila?", a: "Persatuan Indonesia", w: ["Ketuhanan Yang Maha Esa", "Kemanusiaan yang Adil dan Beradab", "Keadilan Sosial bagi Seluruh Rakyat Indonesia"], c: "Kewarganegaraan", d: "easy" },
  { q: "Apa nama lambang negara Indonesia?", a: "Garuda Pancasila", w: ["Elang Jawa", "Merah Putih", "Rajawali Nusantara"], c: "Kewarganegaraan", d: "easy" },

  // --- Sains ---
  { q: "Planet yang paling dekat dengan Matahari adalah?", a: "Merkurius", w: ["Venus", "Mars", "Bumi"], c: "Sains", d: "easy" },
  { q: "Planet terbesar di Tata Surya adalah?", a: "Jupiter", w: ["Saturnus", "Neptunus", "Uranus"], c: "Sains", d: "easy" },
  { q: "Planet yang dijuluki Planet Merah adalah?", a: "Mars", w: ["Venus", "Jupiter", "Merkurius"], c: "Sains", d: "easy" },
  { q: "Apa rumus kimia air?", a: "H2O", w: ["CO2", "NaCl", "O2"], c: "Sains", d: "easy" },
  { q: "Gas yang paling banyak terdapat di atmosfer Bumi adalah?", a: "Nitrogen", w: ["Oksigen", "Karbon dioksida", "Argon"], c: "Sains", d: "medium" },
  { q: "Organ tubuh yang berfungsi memompa darah adalah?", a: "Jantung", w: ["Paru-paru", "Hati", "Ginjal"], c: "Sains", d: "easy" },
  { q: "Tulang terpanjang pada tubuh manusia adalah?", a: "Tulang paha", w: ["Tulang kering", "Tulang lengan atas", "Tulang belakang"], c: "Sains", d: "medium" },
  { q: "Berapa jumlah kaki laba-laba?", a: "8", w: ["6", "10", "12"], c: "Sains", d: "easy" },
  { q: "Hewan mamalia terbesar di dunia adalah?", a: "Paus biru", w: ["Gajah Afrika", "Jerapah", "Kuda nil"], c: "Sains", d: "easy" },
  { q: "Proses tumbuhan membuat makanan dengan bantuan cahaya matahari disebut?", a: "Fotosintesis", w: ["Respirasi", "Transpirasi", "Evaporasi"], c: "Sains", d: "easy" },
  { q: "Pada tekanan normal, air mendidih pada suhu?", a: "100 °C", w: ["90 °C", "80 °C", "120 °C"], c: "Sains", d: "easy" },
  { q: "Apa satuan kuat arus listrik?", a: "Ampere", w: ["Volt", "Ohm", "Watt"], c: "Sains", d: "medium" },
  { q: "Ilmuwan yang merumuskan teori relativitas adalah?", a: "Albert Einstein", w: ["Isaac Newton", "Nikola Tesla", "Galileo Galilei"], c: "Sains", d: "easy" },
  { q: "Apa simbol kimia untuk emas?", a: "Au", w: ["Ag", "Fe", "Cu"], c: "Sains", d: "medium" },
  { q: "Hewan khas Sulawesi yang mirip kerbau bertubuh kecil adalah?", a: "Anoa", w: ["Banteng", "Tapir", "Babirusa"], c: "Sains", d: "medium" },
  { q: "Burung cenderawasih banyak ditemukan di pulau?", a: "Papua", w: ["Sulawesi", "Kalimantan", "Sumatera"], c: "Sains", d: "easy" },

  // --- Matematika ---
  { q: "Berapa hasil dari 7 × 8?", a: "56", w: ["54", "48", "64"], c: "Matematika", d: "easy" },
  { q: "Berapa akar kuadrat dari 144?", a: "12", w: ["14", "11", "16"], c: "Matematika", d: "easy" },
  { q: "Satu jam sama dengan berapa detik?", a: "3600", w: ["360", "6000", "1200"], c: "Matematika", d: "easy" },
  { q: "Bangun datar segi enam memiliki berapa sisi?", a: "6", w: ["5", "7", "8"], c: "Matematika", d: "easy" },
  { q: "Berapa hasil dari 15 × 15?", a: "225", w: ["215", "250", "205"], c: "Matematika", d: "medium" },
  { q: "Berapa 25% dari 200?", a: "50", w: ["25", "40", "75"], c: "Matematika", d: "easy" },

  // --- Olahraga ---
  { q: "Cabang olahraga yang memberi medali emas Olimpiade pertama untuk Indonesia (1992) adalah?", a: "Bulu tangkis", w: ["Angkat besi", "Panahan", "Tinju"], c: "Olahraga", d: "easy" },
  { q: "Susi Susanti adalah atlet legendaris cabang olahraga?", a: "Bulu tangkis", w: ["Renang", "Tenis", "Atletik"], c: "Olahraga", d: "easy" },
  { q: "Berapa jumlah pemain satu tim sepak bola di lapangan?", a: "11", w: ["10", "9", "12"], c: "Olahraga", d: "easy" },
  { q: "Negara mana yang menjuarai Piala Dunia FIFA 2022?", a: "Argentina", w: ["Prancis", "Brasil", "Kroasia"], c: "Olahraga", d: "easy" },
  { q: "Piala Dunia FIFA 2022 diselenggarakan di negara?", a: "Qatar", w: ["Rusia", "Brasil", "Jepang"], c: "Olahraga", d: "easy" },
  { q: "Apa julukan tim nasional sepak bola Indonesia?", a: "Garuda", w: ["Harimau Malaya", "Gajah Perang", "Azkals"], c: "Olahraga", d: "easy" },
  { q: "Asian Games 2018 diselenggarakan di negara?", a: "Indonesia", w: ["Tiongkok", "Korea Selatan", "Jepang"], c: "Olahraga", d: "easy" },
  { q: "Berapa jumlah cincin pada lambang Olimpiade?", a: "5", w: ["4", "6", "7"], c: "Olahraga", d: "easy" },
  { q: "Dalam catur, bidak yang bergerak membentuk huruf L adalah?", a: "Kuda", w: ["Gajah", "Benteng", "Menteri"], c: "Olahraga", d: "easy" },
  { q: "Cristiano Ronaldo berasal dari negara?", a: "Portugal", w: ["Spanyol", "Brasil", "Italia"], c: "Olahraga", d: "easy" },

  // --- Budaya ---
  { q: "Rendang adalah makanan khas dari daerah?", a: "Sumatera Barat", w: ["Jawa Tengah", "Sulawesi Utara", "Aceh"], c: "Budaya", d: "easy" },
  { q: "Pempek adalah makanan khas kota?", a: "Palembang", w: ["Padang", "Medan", "Pontianak"], c: "Budaya", d: "easy" },
  { q: "Gudeg adalah makanan khas kota?", a: "Yogyakarta", w: ["Surabaya", "Bandung", "Makassar"], c: "Budaya", d: "easy" },
  { q: "Tari Kecak berasal dari daerah?", a: "Bali", w: ["Jawa Timur", "Lombok", "Sulawesi Selatan"], c: "Budaya", d: "easy" },
  { q: "Tari Saman berasal dari daerah?", a: "Aceh", w: ["Sumatera Barat", "Riau", "Jawa Barat"], c: "Budaya", d: "easy" },
  { q: "Alat musik angklung berasal dari daerah?", a: "Jawa Barat", w: ["Jawa Timur", "Bali", "Sumatera Barat"], c: "Budaya", d: "easy" },
  { q: "Alat musik sasando berasal dari provinsi?", a: "Nusa Tenggara Timur", w: ["Maluku", "Papua", "Sulawesi Utara"], c: "Budaya", d: "medium" },
  { q: "Rumah Gadang adalah rumah adat dari daerah?", a: "Sumatera Barat", w: ["Sumatera Utara", "Riau", "Jambi"], c: "Budaya", d: "easy" },
  { q: "Rumah adat Tongkonan berasal dari suku?", a: "Toraja", w: ["Bugis", "Dayak", "Batak"], c: "Budaya", d: "medium" },
  { q: "Batik Indonesia diakui UNESCO sebagai Warisan Budaya Takbenda pada tahun?", a: "2009", w: ["2005", "2012", "2015"], c: "Budaya", d: "medium" },
  { q: "Hari Batik Nasional diperingati setiap tanggal?", a: "2 Oktober", w: ["2 Mei", "21 April", "1 Oktober"], c: "Budaya", d: "medium" },
  { q: "Dalam pewayangan, siapa ayah dari Gareng, Petruk, dan Bagong?", a: "Semar", w: ["Arjuna", "Bima", "Togog"], c: "Budaya", d: "medium" },
  { q: "Siapa pencipta lagu Bengawan Solo?", a: "Gesang", w: ["Ismail Marzuki", "Chrisye", "Iwan Fals"], c: "Budaya", d: "medium" },
  { q: "Novel Laskar Pelangi ditulis oleh?", a: "Andrea Hirata", w: ["Tere Liye", "Pramoedya Ananta Toer", "Habiburrahman El Shirazy"], c: "Budaya", d: "easy" },
  { q: "Novel Bumi Manusia ditulis oleh?", a: "Pramoedya Ananta Toer", w: ["Andrea Hirata", "Chairil Anwar", "Dee Lestari"], c: "Budaya", d: "medium" },

  // --- Teknologi & Hiburan ---
  { q: "Siapa pendiri Microsoft?", a: "Bill Gates", w: ["Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"], c: "Teknologi", d: "easy" },
  { q: "TikTok dimiliki oleh perusahaan?", a: "ByteDance", w: ["Tencent", "Alibaba", "Meta"], c: "Teknologi", d: "easy" },
  { q: "Apa kepanjangan dari WWW?", a: "World Wide Web", w: ["World Web Wide", "Wide World Web", "Web World Wide"], c: "Teknologi", d: "easy" },
  { q: "Tokoh kartun spons kuning yang tinggal di dalam nanas di dasar laut adalah?", a: "SpongeBob", w: ["Patrick", "Squidward", "Plankton"], c: "Hiburan", d: "easy" },

  // ===================== Tambahan bank soal =====================

  // --- Geografi: ibu kota provinsi ---
  { q: "Apa ibu kota Provinsi Sumatera Barat?", a: "Padang", w: ["Bukittinggi", "Payakumbuh", "Solok"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Jawa Timur?", a: "Surabaya", w: ["Malang", "Kediri", "Madiun"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Jawa Tengah?", a: "Semarang", w: ["Solo", "Magelang", "Tegal"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Sulawesi Utara?", a: "Manado", w: ["Gorontalo", "Bitung", "Tomohon"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Kalimantan Barat?", a: "Pontianak", w: ["Singkawang", "Ketapang", "Sambas"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Riau?", a: "Pekanbaru", w: ["Dumai", "Tanjung Pinang", "Batam"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Kepulauan Riau?", a: "Tanjung Pinang", w: ["Batam", "Bintan", "Karimun"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Provinsi Aceh?", a: "Banda Aceh", w: ["Lhokseumawe", "Sabang", "Meulaboh"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Lampung?", a: "Bandar Lampung", w: ["Metro", "Kalianda", "Pringsewu"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Nusa Tenggara Barat?", a: "Mataram", w: ["Bima", "Sumbawa Besar", "Praya"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Nusa Tenggara Timur?", a: "Kupang", w: ["Ende", "Maumere", "Labuan Bajo"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Maluku?", a: "Ambon", w: ["Ternate", "Tual", "Masohi"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Maluku Utara?", a: "Sofifi", w: ["Ternate", "Tidore", "Tobelo"], c: "Geografi", d: "hard" },
  { q: "Apa ibu kota Provinsi Sumatera Selatan?", a: "Palembang", w: ["Lubuklinggau", "Prabumulih", "Lahat"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Banten?", a: "Serang", w: ["Tangerang", "Cilegon", "Pandeglang"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Provinsi Sulawesi Tengah?", a: "Palu", w: ["Poso", "Luwuk", "Donggala"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Provinsi Sulawesi Tenggara?", a: "Kendari", w: ["Baubau", "Kolaka", "Raha"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Provinsi Kepulauan Bangka Belitung?", a: "Pangkalpinang", w: ["Tanjung Pandan", "Sungailiat", "Muntok"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Provinsi Kalimantan Tengah?", a: "Palangka Raya", w: ["Sampit", "Pangkalan Bun", "Kuala Kapuas"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Provinsi Kalimantan Utara?", a: "Tanjung Selor", w: ["Tarakan", "Nunukan", "Malinau"], c: "Geografi", d: "hard" },

  // --- Geografi: julukan & Indonesia ---
  { q: "Pulau manakah yang dijuluki Pulau Dewata?", a: "Bali", w: ["Lombok", "Jawa", "Sumatera"], c: "Geografi", d: "easy" },
  { q: "Daerah manakah yang dijuluki Serambi Mekah?", a: "Aceh", w: ["Sumatera Barat", "Banten", "Riau"], c: "Geografi", d: "easy" },
  { q: "Kota manakah yang dijuluki Kota Kretek?", a: "Kudus", w: ["Kediri", "Jepara", "Pati"], c: "Geografi", d: "medium" },
  { q: "Kota manakah yang dijuluki Kota Ukir?", a: "Jepara", w: ["Kudus", "Tegal", "Solo"], c: "Geografi", d: "medium" },
  { q: "Kota manakah yang dijuluki Kota Seribu Sungai?", a: "Banjarmasin", w: ["Palembang", "Pontianak", "Samarinda"], c: "Geografi", d: "medium" },
  { q: "Kota manakah yang dijuluki Kota Khatulistiwa?", a: "Pontianak", w: ["Bukittinggi", "Manado", "Palu"], c: "Geografi", d: "easy" },
  { q: "Kota manakah yang dijuluki Kota Daeng?", a: "Makassar", w: ["Manado", "Kendari", "Palu"], c: "Geografi", d: "medium" },
  { q: "Daerah manakah yang dijuluki Bumi Cenderawasih?", a: "Papua", w: ["Maluku", "Sulawesi", "Kalimantan"], c: "Geografi", d: "easy" },
  { q: "Indonesia saat ini memiliki berapa provinsi?", a: "38", w: ["34", "36", "37"], c: "Geografi", d: "medium" },
  { q: "Indonesia dibagi menjadi berapa zona waktu?", a: "3", w: ["2", "4", "5"], c: "Geografi", d: "easy" },
  { q: "Apa kepanjangan dari WITA?", a: "Waktu Indonesia Tengah", w: ["Waktu Indonesia Timur", "Waktu Indonesia Tenggara", "Waktu Internasional Tengah"], c: "Geografi", d: "easy" },
  { q: "Garis khayal yang membagi Bumi menjadi belahan utara dan selatan disebut?", a: "Khatulistiwa", w: ["Garis bujur", "Garis balik utara", "Meridian Greenwich"], c: "Geografi", d: "easy" },
  { q: "Taman Nasional Ujung Kulon terkenal sebagai habitat?", a: "Badak Jawa", w: ["Harimau Sumatera", "Orangutan", "Komodo"], c: "Geografi", d: "medium" },
  { q: "Orangutan hidup secara alami di pulau?", a: "Kalimantan dan Sumatera", w: ["Jawa dan Bali", "Sulawesi dan Papua", "Papua dan Maluku"], c: "Geografi", d: "easy" },
  { q: "Gunung berapi yang meletus sangat dahsyat pada tahun 1815 adalah?", a: "Gunung Tambora", w: ["Gunung Krakatau", "Gunung Merapi", "Gunung Kelud"], c: "Geografi", d: "medium" },
  { q: "Letusan besar Gunung Krakatau terjadi pada tahun?", a: "1883", w: ["1815", "1906", "1963"], c: "Geografi", d: "medium" },
  { q: "Danau Kelimutu yang airnya tiga warna terletak di pulau?", a: "Flores", w: ["Sumba", "Timor", "Lombok"], c: "Geografi", d: "medium" },
  { q: "Gunung Bromo terletak di provinsi?", a: "Jawa Timur", w: ["Jawa Tengah", "Jawa Barat", "Bali"], c: "Geografi", d: "easy" },
  { q: "Pulau Nusakambangan terletak di dekat kota?", a: "Cilacap", w: ["Semarang", "Tegal", "Pekalongan"], c: "Geografi", d: "medium" },
  { q: "Selat yang memisahkan Pulau Sumatera dan Semenanjung Malaysia adalah?", a: "Selat Malaka", w: ["Selat Sunda", "Selat Karimata", "Selat Makassar"], c: "Geografi", d: "easy" },
  { q: "Pura Tanah Lot terletak di pulau?", a: "Bali", w: ["Lombok", "Jawa", "Sumbawa"], c: "Geografi", d: "easy" },
  { q: "Sirkuit Mandalika berada di pulau?", a: "Lombok", w: ["Bali", "Sumbawa", "Jawa"], c: "Geografi", d: "easy" },

  // --- Geografi: dunia ---
  { q: "Gunung tertinggi di dunia adalah?", a: "Gunung Everest", w: ["K2", "Kilimanjaro", "Mont Blanc"], c: "Geografi", d: "easy" },
  { q: "Negara terluas di dunia adalah?", a: "Rusia", w: ["Kanada", "Tiongkok", "Amerika Serikat"], c: "Geografi", d: "easy" },
  { q: "Negara terkecil di dunia adalah?", a: "Vatikan", w: ["Monako", "Singapura", "San Marino"], c: "Geografi", d: "easy" },
  { q: "Gurun pasir panas terluas di dunia adalah?", a: "Gurun Sahara", w: ["Gurun Gobi", "Gurun Kalahari", "Gurun Atacama"], c: "Geografi", d: "easy" },
  { q: "Danau terluas di dunia adalah?", a: "Laut Kaspia", w: ["Danau Superior", "Danau Victoria", "Danau Baikal"], c: "Geografi", d: "hard" },
  { q: "Apa ibu kota Korea Selatan?", a: "Seoul", w: ["Busan", "Incheon", "Pyongyang"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Thailand?", a: "Bangkok", w: ["Chiang Mai", "Phuket", "Pattaya"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Filipina?", a: "Manila", w: ["Cebu", "Davao", "Quezon City"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Vietnam?", a: "Hanoi", w: ["Ho Chi Minh City", "Da Nang", "Hue"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Malaysia?", a: "Kuala Lumpur", w: ["Johor Bahru", "Penang", "Malaka"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Timor Leste?", a: "Dili", w: ["Baucau", "Suai", "Maliana"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Arab Saudi?", a: "Riyadh", w: ["Jeddah", "Mekah", "Madinah"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Mesir?", a: "Kairo", w: ["Alexandria", "Luxor", "Giza"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Brasil?", a: "Brasilia", w: ["Rio de Janeiro", "Sao Paulo", "Salvador"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Kanada?", a: "Ottawa", w: ["Toronto", "Vancouver", "Montreal"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Turki?", a: "Ankara", w: ["Istanbul", "Izmir", "Antalya"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Italia?", a: "Roma", w: ["Milan", "Venesia", "Napoli"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Jerman?", a: "Berlin", w: ["Munich", "Hamburg", "Frankfurt"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Spanyol?", a: "Madrid", w: ["Barcelona", "Sevilla", "Valencia"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Belanda?", a: "Amsterdam", w: ["Rotterdam", "Utrecht", "Eindhoven"], c: "Geografi", d: "easy" },
  { q: "Apa nama mata uang Thailand?", a: "Baht", w: ["Ringgit", "Won", "Rupee"], c: "Geografi", d: "easy" },
  { q: "Apa nama mata uang Korea Selatan?", a: "Won", w: ["Yen", "Yuan", "Dong"], c: "Geografi", d: "easy" },
  { q: "Apa nama mata uang Inggris?", a: "Poundsterling", w: ["Euro", "Dolar", "Franc"], c: "Geografi", d: "easy" },
  { q: "Apa nama mata uang Arab Saudi?", a: "Riyal", w: ["Dirham", "Dinar", "Lira"], c: "Geografi", d: "medium" },
  { q: "Apa nama mata uang India?", a: "Rupee", w: ["Taka", "Rupiah", "Ringgit"], c: "Geografi", d: "easy" },
  { q: "Apa nama mata uang Vietnam?", a: "Dong", w: ["Kip", "Riel", "Baht"], c: "Geografi", d: "medium" },
  { q: "Patung Liberty berada di kota?", a: "New York", w: ["Washington D.C.", "Los Angeles", "Chicago"], c: "Geografi", d: "easy" },
  { q: "Tembok Besar yang terkenal di dunia berada di negara?", a: "Tiongkok", w: ["Jepang", "Mongolia", "Korea Selatan"], c: "Geografi", d: "easy" },
  { q: "Piramida Giza berada di negara?", a: "Mesir", w: ["Meksiko", "Irak", "Sudan"], c: "Geografi", d: "easy" },
  { q: "Taj Mahal berada di negara?", a: "India", w: ["Pakistan", "Bangladesh", "Iran"], c: "Geografi", d: "easy" },
  { q: "Menara Pisa yang miring berada di negara?", a: "Italia", w: ["Prancis", "Spanyol", "Yunani"], c: "Geografi", d: "easy" },
  { q: "Negara manakah yang dijuluki Negeri Sakura?", a: "Jepang", w: ["Korea Selatan", "Tiongkok", "Taiwan"], c: "Geografi", d: "easy" },
  { q: "Negara manakah yang dijuluki Negeri Gajah Putih?", a: "Thailand", w: ["India", "Myanmar", "Laos"], c: "Geografi", d: "easy" },
  { q: "Negara manakah yang dijuluki Negeri Kincir Angin?", a: "Belanda", w: ["Belgia", "Denmark", "Jerman"], c: "Geografi", d: "easy" },
  { q: "Negara manakah yang dijuluki Negeri Kanguru?", a: "Australia", w: ["Selandia Baru", "Papua Nugini", "Afrika Selatan"], c: "Geografi", d: "easy" },
  { q: "Negara manakah yang dijuluki Negeri Tirai Bambu?", a: "Tiongkok", w: ["Jepang", "Vietnam", "Korea Utara"], c: "Geografi", d: "easy" },
  { q: "Negara manakah yang dijuluki Negeri Ginseng?", a: "Korea Selatan", w: ["Jepang", "Tiongkok", "Mongolia"], c: "Geografi", d: "easy" },

  // --- Sejarah ---
  { q: "Siapa presiden kedua Republik Indonesia?", a: "Soeharto", w: ["Soekarno", "B.J. Habibie", "Adam Malik"], c: "Sejarah", d: "easy" },
  { q: "Siapa presiden kelima Republik Indonesia?", a: "Megawati Soekarnoputri", w: ["Abdurrahman Wahid", "Susilo Bambang Yudhoyono", "B.J. Habibie"], c: "Sejarah", d: "easy" },
  { q: "Siapa presiden keenam Republik Indonesia?", a: "Susilo Bambang Yudhoyono", w: ["Megawati Soekarnoputri", "Joko Widodo", "Jusuf Kalla"], c: "Sejarah", d: "easy" },
  { q: "Siapa presiden ketujuh Republik Indonesia?", a: "Joko Widodo", w: ["Susilo Bambang Yudhoyono", "Prabowo Subianto", "Jusuf Kalla"], c: "Sejarah", d: "easy" },
  { q: "Siapa presiden kedelapan Republik Indonesia?", a: "Prabowo Subianto", w: ["Joko Widodo", "Anies Baswedan", "Ganjar Pranowo"], c: "Sejarah", d: "easy" },
  { q: "Siapa yang mengetik naskah Proklamasi Kemerdekaan Indonesia?", a: "Sayuti Melik", w: ["Soekarno", "Ahmad Soebardjo", "Sukarni"], c: "Sejarah", d: "medium" },
  { q: "Proklamasi kemerdekaan dibacakan di Jalan?", a: "Pegangsaan Timur 56", w: ["Menteng 31", "Imam Bonjol 1", "Merdeka Utara"], c: "Sejarah", d: "medium" },
  { q: "Peristiwa pengamanan Soekarno–Hatta oleh golongan muda sebelum proklamasi dikenal sebagai peristiwa?", a: "Rengasdengklok", w: ["Bandung Lautan Api", "Linggarjati", "Renville"], c: "Sejarah", d: "easy" },
  { q: "Peristiwa Bandung Lautan Api terjadi pada tahun?", a: "1946", w: ["1945", "1947", "1948"], c: "Sejarah", d: "medium" },
  { q: "Organisasi Budi Utomo didirikan pada tahun?", a: "1908", w: ["1928", "1912", "1945"], c: "Sejarah", d: "medium" },
  { q: "Hari Kebangkitan Nasional diperingati setiap tanggal?", a: "20 Mei", w: ["2 Mei", "1 Juni", "28 Oktober"], c: "Sejarah", d: "easy" },
  { q: "Hari Kesaktian Pancasila diperingati setiap tanggal?", a: "1 Oktober", w: ["30 September", "1 Juni", "17 Agustus"], c: "Sejarah", d: "easy" },
  { q: "Hari Lahir Pancasila diperingati setiap tanggal?", a: "1 Juni", w: ["1 Oktober", "18 Agustus", "20 Mei"], c: "Sejarah", d: "easy" },
  { q: "Hari Ibu di Indonesia diperingati setiap tanggal?", a: "22 Desember", w: ["21 April", "8 Maret", "12 Desember"], c: "Sejarah", d: "easy" },
  { q: "Hari Sumpah Pemuda diperingati setiap tanggal?", a: "28 Oktober", w: ["20 Mei", "10 November", "1 Oktober"], c: "Sejarah", d: "easy" },
  { q: "Hari Guru Nasional diperingati setiap tanggal?", a: "25 November", w: ["2 Mei", "20 Mei", "10 November"], c: "Sejarah", d: "medium" },
  { q: "Kerajaan maritim bercorak Buddha yang berpusat di Palembang adalah?", a: "Sriwijaya", w: ["Majapahit", "Kutai", "Tarumanegara"], c: "Sejarah", d: "easy" },
  { q: "Raja Majapahit yang memerintah pada masa kejayaan bersama Gajah Mada adalah?", a: "Hayam Wuruk", w: ["Raden Wijaya", "Ken Arok", "Airlangga"], c: "Sejarah", d: "medium" },
  { q: "Kerajaan Islam pertama di Pulau Jawa adalah?", a: "Demak", w: ["Banten", "Mataram Islam", "Cirebon"], c: "Sejarah", d: "medium" },
  { q: "Siapa pendiri organisasi Muhammadiyah?", a: "K.H. Ahmad Dahlan", w: ["K.H. Hasyim Asy'ari", "H.O.S. Tjokroaminoto", "Ki Hajar Dewantara"], c: "Sejarah", d: "easy" },
  { q: "Siapa pendiri organisasi Nahdlatul Ulama?", a: "K.H. Hasyim Asy'ari", w: ["K.H. Ahmad Dahlan", "Abdurrahman Wahid", "K.H. Wahid Hasyim"], c: "Sejarah", d: "easy" },
  { q: "Kapitan Pattimura adalah pahlawan nasional dari daerah?", a: "Maluku", w: ["Sulawesi Utara", "Papua", "Bali"], c: "Sejarah", d: "easy" },
  { q: "Pahlawan yang dijuluki Ayam Jantan dari Timur adalah?", a: "Sultan Hasanuddin", w: ["Kapitan Pattimura", "Sultan Agung", "Teuku Umar"], c: "Sejarah", d: "medium" },
  { q: "Tuanku Imam Bonjol memimpin perang melawan Belanda yang disebut?", a: "Perang Padri", w: ["Perang Diponegoro", "Perang Aceh", "Perang Puputan"], c: "Sejarah", d: "medium" },
  { q: "Negara yang paling lama menjajah Indonesia adalah?", a: "Belanda", w: ["Jepang", "Portugis", "Inggris"], c: "Sejarah", d: "easy" },
  { q: "Jepang menduduki Indonesia selama kurang lebih?", a: "3,5 tahun", w: ["1 tahun", "10 tahun", "30 tahun"], c: "Sejarah", d: "easy" },
  { q: "VOC adalah persekutuan dagang milik negara?", a: "Belanda", w: ["Inggris", "Portugis", "Spanyol"], c: "Sejarah", d: "easy" },
  { q: "Siapa perancang lambang negara Garuda Pancasila?", a: "Sultan Hamid II", w: ["Mohammad Yamin", "Soekarno", "Ki Hajar Dewantara"], c: "Sejarah", d: "hard" },
  { q: "Candi Borobudur dibangun pada masa dinasti?", a: "Syailendra", w: ["Sanjaya", "Rajasa", "Isyana"], c: "Sejarah", d: "hard" },
  { q: "Perang Dunia II berakhir pada tahun?", a: "1945", w: ["1939", "1942", "1950"], c: "Sejarah", d: "easy" },
  { q: "Siapa manusia pertama yang menginjakkan kaki di Bulan?", a: "Neil Armstrong", w: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"], c: "Sejarah", d: "easy" },
  { q: "Manusia pertama kali mendarat di Bulan pada tahun?", a: "1969", w: ["1959", "1972", "1981"], c: "Sejarah", d: "medium" },
  { q: "Siapa manusia pertama yang pergi ke luar angkasa?", a: "Yuri Gagarin", w: ["Neil Armstrong", "John Glenn", "Valentina Tereshkova"], c: "Sejarah", d: "medium" },
  { q: "Candi Prambanan merupakan candi bercorak agama?", a: "Hindu", w: ["Buddha", "Islam", "Konghucu"], c: "Sejarah", d: "easy" },
  { q: "Candi Borobudur merupakan candi bercorak agama?", a: "Buddha", w: ["Hindu", "Islam", "Kristen"], c: "Sejarah", d: "easy" },

  // --- Kewarganegaraan ---
  { q: "Lambang sila pertama Pancasila adalah?", a: "Bintang", w: ["Rantai", "Pohon beringin", "Kepala banteng"], c: "Kewarganegaraan", d: "easy" },
  { q: "Lambang sila kedua Pancasila adalah?", a: "Rantai", w: ["Bintang", "Padi dan kapas", "Pohon beringin"], c: "Kewarganegaraan", d: "easy" },
  { q: "Lambang sila ketiga Pancasila adalah?", a: "Pohon beringin", w: ["Kepala banteng", "Rantai", "Bintang"], c: "Kewarganegaraan", d: "easy" },
  { q: "Lambang sila keempat Pancasila adalah?", a: "Kepala banteng", w: ["Pohon beringin", "Padi dan kapas", "Rantai"], c: "Kewarganegaraan", d: "easy" },
  { q: "Lambang sila kelima Pancasila adalah?", a: "Padi dan kapas", w: ["Bintang", "Kepala banteng", "Pohon beringin"], c: "Kewarganegaraan", d: "easy" },
  { q: "Berapa jumlah bulu pada masing-masing sayap Garuda Pancasila?", a: "17", w: ["8", "19", "45"], c: "Kewarganegaraan", d: "medium" },
  { q: "Berapa jumlah bulu pada ekor Garuda Pancasila?", a: "8", w: ["17", "19", "45"], c: "Kewarganegaraan", d: "medium" },
  { q: "Berapa jumlah bulu pada leher Garuda Pancasila?", a: "45", w: ["17", "8", "19"], c: "Kewarganegaraan", d: "medium" },
  { q: "Masa jabatan Presiden Republik Indonesia dalam satu periode adalah?", a: "5 tahun", w: ["4 tahun", "6 tahun", "7 tahun"], c: "Kewarganegaraan", d: "easy" },
  { q: "Apa kepanjangan dari DPR?", a: "Dewan Perwakilan Rakyat", w: ["Dewan Pimpinan Rakyat", "Dewan Perwakilan Republik", "Dinas Perwakilan Rakyat"], c: "Kewarganegaraan", d: "easy" },
  { q: "Apa kepanjangan dari MPR?", a: "Majelis Permusyawaratan Rakyat", w: ["Majelis Perwakilan Rakyat", "Musyawarah Perwakilan Rakyat", "Majelis Pimpinan Republik"], c: "Kewarganegaraan", d: "easy" },
  { q: "Apa kepanjangan dari KPK?", a: "Komisi Pemberantasan Korupsi", w: ["Komisi Pengawas Keuangan", "Komite Pemberantasan Korupsi", "Komisi Pemeriksa Kekayaan"], c: "Kewarganegaraan", d: "easy" },
  { q: "Lembaga yang menyelenggarakan pemilihan umum di Indonesia adalah?", a: "KPU", w: ["KPK", "MK", "BPK"], c: "Kewarganegaraan", d: "easy" },
  { q: "Bank sentral Republik Indonesia adalah?", a: "Bank Indonesia", w: ["Bank Mandiri", "Bank Rakyat Indonesia", "Otoritas Jasa Keuangan"], c: "Kewarganegaraan", d: "easy" },
  { q: "Lembaga yang memberikan informasi cuaca dan gempa di Indonesia adalah?", a: "BMKG", w: ["BNPB", "BPS", "LAPAN"], c: "Kewarganegaraan", d: "easy" },
  { q: "Satwa yang ditetapkan sebagai Satwa Nasional Indonesia adalah?", a: "Komodo", w: ["Elang Jawa", "Harimau Sumatera", "Orangutan"], c: "Kewarganegaraan", d: "medium" },
  { q: "Bunga yang ditetapkan sebagai Puspa Bangsa Indonesia adalah?", a: "Melati putih", w: ["Mawar merah", "Anggrek bulan", "Rafflesia arnoldii"], c: "Kewarganegaraan", d: "medium" },
  { q: "Bunga yang ditetapkan sebagai Puspa Pesona Indonesia adalah?", a: "Anggrek bulan", w: ["Melati putih", "Rafflesia arnoldii", "Bunga matahari"], c: "Kewarganegaraan", d: "hard" },

  // --- Sains ---
  { q: "Planet yang terkenal dengan cincinnya yang indah adalah?", a: "Saturnus", w: ["Jupiter", "Mars", "Venus"], c: "Sains", d: "easy" },
  { q: "Berapa jumlah planet di Tata Surya?", a: "8", w: ["7", "9", "10"], c: "Sains", d: "easy" },
  { q: "Planet yang paling jauh dari Matahari adalah?", a: "Neptunus", w: ["Uranus", "Pluto", "Saturnus"], c: "Sains", d: "medium" },
  { q: "Planet terpanas di Tata Surya adalah?", a: "Venus", w: ["Merkurius", "Mars", "Jupiter"], c: "Sains", d: "hard" },
  { q: "Bintang yang paling dekat dengan Bumi adalah?", a: "Matahari", w: ["Proxima Centauri", "Sirius", "Polaris"], c: "Sains", d: "medium" },
  { q: "Benda langit yang memiliki ekor dan mengelilingi Matahari disebut?", a: "Komet", w: ["Meteor", "Asteroid", "Satelit"], c: "Sains", d: "easy" },
  { q: "Bumi berotasi satu kali dalam waktu sekitar?", a: "24 jam", w: ["12 jam", "30 hari", "365 hari"], c: "Sains", d: "easy" },
  { q: "Bumi mengelilingi Matahari satu kali dalam waktu sekitar?", a: "365 hari", w: ["30 hari", "24 jam", "180 hari"], c: "Sains", d: "easy" },
  { q: "Apa rumus kimia garam dapur?", a: "NaCl", w: ["H2O", "CO2", "KCl"], c: "Sains", d: "easy" },
  { q: "CO2 adalah rumus kimia dari?", a: "Karbon dioksida", w: ["Karbon monoksida", "Oksigen", "Metana"], c: "Sains", d: "easy" },
  { q: "Gas yang dihasilkan tumbuhan saat fotosintesis adalah?", a: "Oksigen", w: ["Karbon dioksida", "Nitrogen", "Hidrogen"], c: "Sains", d: "easy" },
  { q: "Apa simbol kimia untuk besi?", a: "Fe", w: ["Au", "Ag", "Pb"], c: "Sains", d: "medium" },
  { q: "Apa simbol kimia untuk perak?", a: "Ag", w: ["Au", "Pt", "Pb"], c: "Sains", d: "medium" },
  { q: "Unsur kimia yang paling ringan adalah?", a: "Hidrogen", w: ["Helium", "Oksigen", "Litium"], c: "Sains", d: "medium" },
  { q: "Air murni memiliki pH sebesar?", a: "7", w: ["0", "5", "14"], c: "Sains", d: "medium" },
  { q: "Pada tekanan normal, air membeku pada suhu?", a: "0 °C", w: ["10 °C", "32 °C", "4 °C"], c: "Sains", d: "easy" },
  { q: "Kecepatan cahaya di ruang hampa kira-kira?", a: "300.000 km/detik", w: ["3.000 km/detik", "30.000 km/detik", "3.000.000 km/detik"], c: "Sains", d: "medium" },
  { q: "Apa satuan tegangan listrik?", a: "Volt", w: ["Ampere", "Ohm", "Watt"], c: "Sains", d: "easy" },
  { q: "Apa satuan hambatan listrik?", a: "Ohm", w: ["Volt", "Ampere", "Joule"], c: "Sains", d: "medium" },
  { q: "Apa satuan gaya?", a: "Newton", w: ["Joule", "Watt", "Pascal"], c: "Sains", d: "medium" },
  { q: "Apa satuan energi?", a: "Joule", w: ["Newton", "Volt", "Kelvin"], c: "Sains", d: "medium" },
  { q: "Ilmuwan yang terkenal dengan hukum gravitasi setelah melihat apel jatuh adalah?", a: "Isaac Newton", w: ["Albert Einstein", "Galileo Galilei", "Thomas Edison"], c: "Sains", d: "easy" },
  { q: "Siapa penemu penisilin?", a: "Alexander Fleming", w: ["Louis Pasteur", "Marie Curie", "Robert Koch"], c: "Sains", d: "medium" },
  { q: "Siapa penemu telepon?", a: "Alexander Graham Bell", w: ["Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"], c: "Sains", d: "easy" },
  { q: "Pesawat terbang bermotor pertama diciptakan oleh?", a: "Wright bersaudara", w: ["Thomas Edison", "B.J. Habibie", "Leonardo da Vinci"], c: "Sains", d: "easy" },
  { q: "Organ tubuh manusia yang digunakan untuk bernapas adalah?", a: "Paru-paru", w: ["Jantung", "Lambung", "Ginjal"], c: "Sains", d: "easy" },
  { q: "Organ yang menyaring darah dan menghasilkan urin adalah?", a: "Ginjal", w: ["Hati", "Limpa", "Lambung"], c: "Sains", d: "easy" },
  { q: "Berapa jumlah tulang pada tubuh manusia dewasa?", a: "206", w: ["106", "186", "306"], c: "Sains", d: "medium" },
  { q: "Jantung manusia terdiri dari berapa ruang?", a: "4", w: ["2", "3", "5"], c: "Sains", d: "easy" },
  { q: "Golongan darah yang disebut donor universal adalah?", a: "O", w: ["A", "B", "AB"], c: "Sains", d: "medium" },
  { q: "Sel darah yang berperan dalam pembekuan darah adalah?", a: "Trombosit", w: ["Eritrosit", "Leukosit", "Plasma"], c: "Sains", d: "medium" },
  { q: "Sel darah merah disebut juga?", a: "Eritrosit", w: ["Leukosit", "Trombosit", "Limfosit"], c: "Sains", d: "medium" },
  { q: "Vitamin yang dapat dibentuk kulit dengan bantuan sinar matahari adalah?", a: "Vitamin D", w: ["Vitamin A", "Vitamin C", "Vitamin K"], c: "Sains", d: "easy" },
  { q: "Kekurangan vitamin A dapat menyebabkan?", a: "Rabun senja", w: ["Sariawan", "Rakitis", "Beri-beri"], c: "Sains", d: "easy" },
  { q: "Kekurangan vitamin C dapat menyebabkan?", a: "Sariawan", w: ["Rabun senja", "Rakitis", "Anemia"], c: "Sains", d: "easy" },
  { q: "Zat hijau daun pada tumbuhan disebut?", a: "Klorofil", w: ["Stomata", "Xilem", "Floem"], c: "Sains", d: "easy" },
  { q: "Hewan yang hanya memakan tumbuhan disebut?", a: "Herbivora", w: ["Karnivora", "Omnivora", "Insektivora"], c: "Sains", d: "easy" },
  { q: "Hewan pemakan segala disebut?", a: "Omnivora", w: ["Herbivora", "Karnivora", "Detritivora"], c: "Sains", d: "easy" },
  { q: "Hewan darat tercepat di dunia adalah?", a: "Cheetah", w: ["Singa", "Kuda", "Rusa"], c: "Sains", d: "easy" },
  { q: "Burung terbesar di dunia adalah?", a: "Burung unta", w: ["Elang", "Pelikan", "Albatros"], c: "Sains", d: "easy" },
  { q: "Satu-satunya mamalia yang dapat terbang adalah?", a: "Kelelawar", w: ["Burung hantu", "Kupu-kupu", "Ayam"], c: "Sains", d: "easy" },
  { q: "Berapa jumlah kaki serangga?", a: "6", w: ["4", "8", "10"], c: "Sains", d: "easy" },
  { q: "Anak katak yang masih hidup di air disebut?", a: "Berudu", w: ["Ulat", "Nimfa", "Pupa"], c: "Sains", d: "easy" },
  { q: "Alat untuk mengukur suhu adalah?", a: "Termometer", w: ["Barometer", "Higrometer", "Anemometer"], c: "Sains", d: "easy" },
  { q: "Alat untuk mengukur tekanan udara adalah?", a: "Barometer", w: ["Termometer", "Seismograf", "Speedometer"], c: "Sains", d: "medium" },
  { q: "Alat untuk mencatat getaran gempa bumi adalah?", a: "Seismograf", w: ["Barometer", "Termometer", "Higrometer"], c: "Sains", d: "medium" },
  { q: "Lapisan atmosfer tempat terjadinya cuaca adalah?", a: "Troposfer", w: ["Stratosfer", "Mesosfer", "Termosfer"], c: "Sains", d: "hard" },
  { q: "Berapa jumlah warna pelangi?", a: "7", w: ["5", "6", "8"], c: "Sains", d: "easy" },
  { q: "Dua kutub magnet yang sejenis jika didekatkan akan?", a: "Tolak-menolak", w: ["Tarik-menarik", "Diam saja", "Menempel"], c: "Sains", d: "easy" },
  { q: "Ilmu yang mempelajari cuaca disebut?", a: "Meteorologi", w: ["Geologi", "Astronomi", "Biologi"], c: "Sains", d: "medium" },
  { q: "Ilmu yang mempelajari benda-benda langit disebut?", a: "Astronomi", w: ["Astrologi", "Geografi", "Meteorologi"], c: "Sains", d: "easy" },

  // --- Matematika ---
  { q: "Berapa hasil dari 12 × 12?", a: "144", w: ["124", "132", "154"], c: "Matematika", d: "easy" },
  { q: "Berapa hasil dari 9 × 9?", a: "81", w: ["72", "79", "90"], c: "Matematika", d: "easy" },
  { q: "Berapa hasil dari 100 ÷ 4?", a: "25", w: ["20", "40", "24"], c: "Matematika", d: "easy" },
  { q: "Berapa hasil dari 2 pangkat 10?", a: "1024", w: ["1000", "512", "2048"], c: "Matematika", d: "medium" },
  { q: "Berapa akar kuadrat dari 81?", a: "9", w: ["8", "7", "11"], c: "Matematika", d: "easy" },
  { q: "Berapa hasil dari 6 + 4 × 2?", a: "14", w: ["20", "16", "12"], c: "Matematika", d: "medium" },
  { q: "Berapa jumlah besar sudut dalam sebuah segitiga?", a: "180°", w: ["90°", "360°", "270°"], c: "Matematika", d: "easy" },
  { q: "Sudut siku-siku besarnya?", a: "90°", w: ["45°", "180°", "60°"], c: "Matematika", d: "easy" },
  { q: "Keliling persegi dengan sisi 5 cm adalah?", a: "20 cm", w: ["25 cm", "10 cm", "15 cm"], c: "Matematika", d: "easy" },
  { q: "Luas persegi dengan sisi 6 cm adalah?", a: "36 cm²", w: ["24 cm²", "12 cm²", "30 cm²"], c: "Matematika", d: "easy" },
  { q: "Angka Romawi X bernilai?", a: "10", w: ["5", "50", "100"], c: "Matematika", d: "easy" },
  { q: "Angka Romawi L bernilai?", a: "50", w: ["5", "100", "500"], c: "Matematika", d: "medium" },
  { q: "Angka Romawi C bernilai?", a: "100", w: ["50", "500", "1000"], c: "Matematika", d: "medium" },
  { q: "Bilangan prima terkecil adalah?", a: "2", w: ["1", "3", "0"], c: "Matematika", d: "medium" },
  { q: "Satu lusin sama dengan berapa buah?", a: "12", w: ["10", "20", "24"], c: "Matematika", d: "easy" },
  { q: "Satu kodi sama dengan berapa buah?", a: "20", w: ["12", "10", "24"], c: "Matematika", d: "easy" },
  { q: "Satu rim kertas berisi berapa lembar?", a: "500", w: ["100", "250", "1000"], c: "Matematika", d: "medium" },
  { q: "Satu gros sama dengan berapa buah?", a: "144", w: ["100", "120", "12"], c: "Matematika", d: "medium" },
  { q: "Satu abad sama dengan berapa tahun?", a: "100", w: ["10", "50", "1000"], c: "Matematika", d: "easy" },
  { q: "Satu windu sama dengan berapa tahun?", a: "8", w: ["5", "10", "12"], c: "Matematika", d: "medium" },
  { q: "Satu dasawarsa sama dengan berapa tahun?", a: "10", w: ["5", "8", "100"], c: "Matematika", d: "easy" },
  { q: "Satu kilometer sama dengan berapa meter?", a: "1000", w: ["100", "10.000", "10"], c: "Matematika", d: "easy" },
  { q: "Bangun datar segi lima disebut juga?", a: "Pentagon", w: ["Heksagon", "Oktagon", "Trapesium"], c: "Matematika", d: "easy" },
  { q: "Berapa 50% dari 80?", a: "40", w: ["30", "50", "60"], c: "Matematika", d: "easy" },
  { q: "Pecahan 3/4 jika diubah ke persen menjadi?", a: "75%", w: ["34%", "43%", "70%"], c: "Matematika", d: "easy" },
  { q: "Nilai pi (π) jika dibulatkan dua angka di belakang koma adalah?", a: "3,14", w: ["3,41", "3,12", "2,14"], c: "Matematika", d: "easy" },
  { q: "Tahun kabisat memiliki berapa hari?", a: "366", w: ["365", "364", "360"], c: "Matematika", d: "easy" },

  // --- Olahraga ---
  { q: "Berapa jumlah pemain satu tim bola basket di lapangan?", a: "5", w: ["6", "7", "11"], c: "Olahraga", d: "easy" },
  { q: "Berapa jumlah pemain satu tim bola voli di lapangan?", a: "6", w: ["5", "7", "9"], c: "Olahraga", d: "easy" },
  { q: "Berapa lama waktu normal satu pertandingan sepak bola?", a: "90 menit", w: ["60 menit", "80 menit", "120 menit"], c: "Olahraga", d: "easy" },
  { q: "Istilah hattrick dalam sepak bola berarti mencetak berapa gol?", a: "3", w: ["2", "4", "5"], c: "Olahraga", d: "easy" },
  { q: "Taufik Hidayat adalah atlet legendaris cabang olahraga?", a: "Bulu tangkis", w: ["Tenis meja", "Tenis", "Voli"], c: "Olahraga", d: "easy" },
  { q: "Rudy Hartono menjuarai All England sebanyak berapa kali?", a: "8", w: ["5", "6", "10"], c: "Olahraga", d: "hard" },
  { q: "Piala Thomas adalah kejuaraan beregu putra untuk cabang olahraga?", a: "Bulu tangkis", w: ["Tenis", "Tenis meja", "Sepak bola"], c: "Olahraga", d: "easy" },
  { q: "Piala Uber adalah kejuaraan bulu tangkis beregu untuk?", a: "Putri", w: ["Putra", "Campuran", "Junior"], c: "Olahraga", d: "medium" },
  { q: "Olimpiade 2024 diselenggarakan di kota?", a: "Paris", w: ["Tokyo", "London", "Los Angeles"], c: "Olahraga", d: "easy" },
  { q: "Olimpiade 2028 akan diselenggarakan di kota?", a: "Los Angeles", w: ["Brisbane", "Paris", "Madrid"], c: "Olahraga", d: "medium" },
  { q: "Piala Dunia FIFA 2026 diselenggarakan di negara?", a: "Amerika Serikat, Kanada, dan Meksiko", w: ["Qatar", "Arab Saudi", "Brasil"], c: "Olahraga", d: "easy" },
  { q: "Negara mana yang menjuarai Piala Dunia FIFA 2018?", a: "Prancis", w: ["Kroasia", "Jerman", "Brasil"], c: "Olahraga", d: "easy" },
  { q: "Negara yang paling banyak menjuarai Piala Dunia FIFA adalah?", a: "Brasil", w: ["Jerman", "Italia", "Argentina"], c: "Olahraga", d: "medium" },
  { q: "Muhammad Ali adalah legenda cabang olahraga?", a: "Tinju", w: ["Gulat", "Karate", "Angkat besi"], c: "Olahraga", d: "easy" },
  { q: "Michael Jordan adalah legenda cabang olahraga?", a: "Bola basket", w: ["Bisbol", "Sepak bola", "Golf"], c: "Olahraga", d: "easy" },
  { q: "Valentino Rossi adalah legenda cabang olahraga?", a: "Balap motor", w: ["Formula 1", "Reli mobil", "Balap sepeda"], c: "Olahraga", d: "easy" },
  { q: "Satu putaran lintasan lari standar atletik panjangnya?", a: "400 meter", w: ["200 meter", "500 meter", "1000 meter"], c: "Olahraga", d: "medium" },
  { q: "Jarak lari maraton adalah?", a: "42,195 km", w: ["21,1 km", "10 km", "50 km"], c: "Olahraga", d: "medium" },
  { q: "Istilah skak mat digunakan dalam permainan?", a: "Catur", w: ["Dam", "Kartu", "Halma"], c: "Olahraga", d: "easy" },
  { q: "Liliyana Natsir dan Tontowi Ahmad meraih emas Olimpiade di kota?", a: "Rio de Janeiro", w: ["London", "Tokyo", "Beijing"], c: "Olahraga", d: "medium" },
  { q: "Greysia Polii dan Apriyani Rahayu meraih emas Olimpiade di?", a: "Tokyo 2020", w: ["Rio 2016", "London 2012", "Paris 2024"], c: "Olahraga", d: "medium" },
  { q: "Kejuaraan sepak bola antarnegara Asia Tenggara disebut?", a: "Piala AFF", w: ["Piala Asia", "Copa America", "Piala Eropa"], c: "Olahraga", d: "easy" },
  { q: "Stadion Utama Gelora Bung Karno berada di kota?", a: "Jakarta", w: ["Bandung", "Surabaya", "Palembang"], c: "Olahraga", d: "easy" },
  { q: "Pesta olahraga negara-negara Asia Tenggara disebut?", a: "SEA Games", w: ["Asian Games", "Olimpiade", "Commonwealth Games"], c: "Olahraga", d: "easy" },

  // --- Budaya: tarian, tradisi, pakaian ---
  { q: "Tari Pendet berasal dari daerah?", a: "Bali", w: ["Jawa Tengah", "Lombok", "Sumatera Barat"], c: "Budaya", d: "easy" },
  { q: "Tari Jaipong berasal dari daerah?", a: "Jawa Barat", w: ["Jawa Tengah", "Jawa Timur", "Banten"], c: "Budaya", d: "easy" },
  { q: "Tari Piring berasal dari daerah?", a: "Sumatera Barat", w: ["Riau", "Aceh", "Jambi"], c: "Budaya", d: "easy" },
  { q: "Tari Tor-Tor berasal dari suku?", a: "Batak", w: ["Dayak", "Minang", "Toraja"], c: "Budaya", d: "easy" },
  { q: "Kesenian Reog berasal dari kota?", a: "Ponorogo", w: ["Madiun", "Kediri", "Blitar"], c: "Budaya", d: "easy" },
  { q: "Ondel-ondel adalah kesenian khas suku?", a: "Betawi", w: ["Sunda", "Jawa", "Bugis"], c: "Budaya", d: "easy" },
  { q: "Upacara Ngaben adalah tradisi dari daerah?", a: "Bali", w: ["Lombok", "Toraja", "Yogyakarta"], c: "Budaya", d: "easy" },
  { q: "Tradisi lompat batu (Fahombo) berasal dari pulau?", a: "Nias", w: ["Mentawai", "Sumba", "Flores"], c: "Budaya", d: "medium" },
  { q: "Tradisi Pacu Jalur berasal dari provinsi?", a: "Riau", w: ["Jambi", "Sumatera Barat", "Kalimantan Barat"], c: "Budaya", d: "medium" },
  { q: "Karapan sapi adalah tradisi khas pulau?", a: "Madura", w: ["Bali", "Lombok", "Sumbawa"], c: "Budaya", d: "easy" },
  { q: "Tradisi Tabuik berasal dari daerah?", a: "Sumatera Barat", w: ["Aceh", "Bengkulu", "Lampung"], c: "Budaya", d: "hard" },
  { q: "Tradisi Pasola (perang berkuda) berasal dari pulau?", a: "Sumba", w: ["Flores", "Timor", "Alor"], c: "Budaya", d: "medium" },
  { q: "Kain Ulos adalah kain tradisional suku?", a: "Batak", w: ["Minang", "Dayak", "Bugis"], c: "Budaya", d: "easy" },
  { q: "Kain Songket yang terkenal berasal dari kota?", a: "Palembang", w: ["Jambi", "Bengkulu", "Pekanbaru"], c: "Budaya", d: "medium" },
  { q: "Bahasa daerah dengan penutur terbanyak di Indonesia adalah?", a: "Bahasa Jawa", w: ["Bahasa Sunda", "Bahasa Madura", "Bahasa Minang"], c: "Budaya", d: "easy" },
  { q: "Aksara Jawa juga dikenal dengan sebutan?", a: "Hanacaraka", w: ["Pallawa", "Kawi", "Pegon"], c: "Budaya", d: "medium" },

  // --- Budaya: makanan ---
  { q: "Kerak telor adalah makanan khas kota?", a: "Jakarta", w: ["Bandung", "Surabaya", "Semarang"], c: "Budaya", d: "easy" },
  { q: "Rawon adalah makanan khas daerah?", a: "Jawa Timur", w: ["Jawa Barat", "Bali", "Sumatera Utara"], c: "Budaya", d: "easy" },
  { q: "Papeda, makanan khas Papua dan Maluku, terbuat dari?", a: "Sagu", w: ["Beras", "Singkong", "Jagung"], c: "Budaya", d: "easy" },
  { q: "Coto adalah makanan khas kota?", a: "Makassar", w: ["Manado", "Palu", "Kendari"], c: "Budaya", d: "easy" },
  { q: "Soto Banjar berasal dari provinsi?", a: "Kalimantan Selatan", w: ["Kalimantan Timur", "Kalimantan Barat", "Jawa Tengah"], c: "Budaya", d: "easy" },
  { q: "Lumpia adalah makanan khas kota?", a: "Semarang", w: ["Solo", "Malang", "Cirebon"], c: "Budaya", d: "easy" },
  { q: "Bika Ambon sebenarnya adalah kue khas kota?", a: "Medan", w: ["Ambon", "Padang", "Palembang"], c: "Budaya", d: "medium" },
  { q: "Ayam betutu adalah makanan khas daerah?", a: "Bali", w: ["Lombok", "Jawa Timur", "Sulawesi Selatan"], c: "Budaya", d: "easy" },
  { q: "Tempe dibuat dari bahan utama?", a: "Kedelai", w: ["Kacang hijau", "Kacang tanah", "Jagung"], c: "Budaya", d: "easy" },

  // --- Budaya: rumah adat, alat musik, senjata ---
  { q: "Rumah Joglo adalah rumah adat dari daerah?", a: "Jawa Tengah", w: ["Jawa Barat", "Bali", "Sumatera Barat"], c: "Budaya", d: "easy" },
  { q: "Rumah Honai adalah rumah adat dari daerah?", a: "Papua", w: ["Maluku", "Nusa Tenggara Timur", "Sulawesi Tengah"], c: "Budaya", d: "easy" },
  { q: "Rumah Bolon adalah rumah adat suku?", a: "Batak", w: ["Minang", "Melayu", "Nias"], c: "Budaya", d: "medium" },
  { q: "Rumah Lamin adalah rumah adat dari provinsi?", a: "Kalimantan Timur", w: ["Kalimantan Selatan", "Sulawesi Barat", "Riau"], c: "Budaya", d: "medium" },
  { q: "Alat musik Tifa berasal dari daerah?", a: "Papua", w: ["Bali", "Aceh", "Jawa Tengah"], c: "Budaya", d: "easy" },
  { q: "Alat musik Kolintang berasal dari provinsi?", a: "Sulawesi Utara", w: ["Sulawesi Selatan", "Maluku", "Gorontalo"], c: "Budaya", d: "medium" },
  { q: "Alat musik Talempong berasal dari daerah?", a: "Sumatera Barat", w: ["Sumatera Utara", "Jambi", "Bengkulu"], c: "Budaya", d: "medium" },
  { q: "Senjata tradisional Kujang berasal dari daerah?", a: "Jawa Barat", w: ["Jawa Tengah", "Bali", "Banten"], c: "Budaya", d: "easy" },
  { q: "Senjata tradisional Rencong berasal dari daerah?", a: "Aceh", w: ["Sumatera Utara", "Riau", "Sumatera Barat"], c: "Budaya", d: "easy" },
  { q: "Senjata tradisional Mandau berasal dari suku?", a: "Dayak", w: ["Batak", "Bugis", "Asmat"], c: "Budaya", d: "easy" },
  { q: "Senjata tradisional Badik berasal dari daerah?", a: "Sulawesi Selatan", w: ["Sulawesi Utara", "Kalimantan Timur", "Maluku"], c: "Budaya", d: "medium" },

  // --- Budaya: lagu daerah & sastra ---
  { q: "Lagu Ampar-Ampar Pisang berasal dari daerah?", a: "Kalimantan Selatan", w: ["Kalimantan Barat", "Sumatera Utara", "Jawa Barat"], c: "Budaya", d: "easy" },
  { q: "Lagu Rasa Sayange berasal dari daerah?", a: "Maluku", w: ["Papua", "Sulawesi Utara", "Nusa Tenggara Timur"], c: "Budaya", d: "easy" },
  { q: "Lagu Yamko Rambe Yamko berasal dari daerah?", a: "Papua", w: ["Maluku", "Nusa Tenggara Timur", "Sulawesi Tengah"], c: "Budaya", d: "easy" },
  { q: "Lagu Bungong Jeumpa berasal dari daerah?", a: "Aceh", w: ["Sumatera Barat", "Riau", "Jambi"], c: "Budaya", d: "easy" },
  { q: "Lagu Manuk Dadali berasal dari daerah?", a: "Jawa Barat", w: ["Jawa Tengah", "Jawa Timur", "Bali"], c: "Budaya", d: "easy" },
  { q: "Lagu Gundul-Gundul Pacul berasal dari daerah?", a: "Jawa Tengah", w: ["Jawa Barat", "Bali", "Kalimantan Selatan"], c: "Budaya", d: "easy" },
  { q: "Lagu Sipatokaan berasal dari daerah?", a: "Sulawesi Utara", w: ["Sulawesi Selatan", "Maluku", "Papua"], c: "Budaya", d: "medium" },
  { q: "Siapa pencipta lagu Hari Merdeka (17 Agustus Tahun 45)?", a: "H. Mutahar", w: ["W.R. Supratman", "Ismail Marzuki", "Gesang"], c: "Budaya", d: "hard" },
  { q: "Berapa jumlah anggota Pandawa dalam kisah Mahabharata?", a: "5", w: ["3", "4", "7"], c: "Budaya", d: "easy" },
  { q: "Siapa anggota Pandawa yang paling tua?", a: "Yudistira", w: ["Bima", "Arjuna", "Nakula"], c: "Budaya", d: "medium" },
  { q: "Dalam kisah Ramayana, siapa yang menculik Dewi Sinta?", a: "Rahwana", w: ["Hanoman", "Rama", "Laksmana"], c: "Budaya", d: "easy" },
  { q: "Kera putih yang membantu Rama dalam kisah Ramayana adalah?", a: "Hanoman", w: ["Sugriwa", "Subali", "Anggada"], c: "Budaya", d: "easy" },
  { q: "Penyair yang terkenal dengan puisi Aku (Binatang Jalang) adalah?", a: "Chairil Anwar", w: ["W.S. Rendra", "Taufiq Ismail", "Sapardi Djoko Damono"], c: "Budaya", d: "easy" },
  { q: "Novel Siti Nurbaya ditulis oleh?", a: "Marah Rusli", w: ["Abdul Muis", "Hamka", "Sutan Takdir Alisjahbana"], c: "Budaya", d: "medium" },
  { q: "Novel Tenggelamnya Kapal Van der Wijck ditulis oleh?", a: "Hamka", w: ["Marah Rusli", "Pramoedya Ananta Toer", "Chairil Anwar"], c: "Budaya", d: "medium" },
  { q: "Novel Ayat-Ayat Cinta ditulis oleh?", a: "Habiburrahman El Shirazy", w: ["Andrea Hirata", "Tere Liye", "Asma Nadia"], c: "Budaya", d: "easy" },
  { q: "Novel Dilan: Dia adalah Dilanku Tahun 1990 ditulis oleh?", a: "Pidi Baiq", w: ["Tere Liye", "Raditya Dika", "Dee Lestari"], c: "Budaya", d: "easy" },
  { q: "Serial novel Supernova ditulis oleh?", a: "Dee Lestari", w: ["Ayu Utami", "Leila S. Chudori", "Tere Liye"], c: "Budaya", d: "medium" },

  // --- Bahasa Indonesia ---
  { q: "Manakah penulisan kata baku yang benar?", a: "Apotek", w: ["Apotik", "Apotiek", "Apoteek"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Praktik", w: ["Praktek", "Peraktik", "Praktyk"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Risiko", w: ["Resiko", "Resico", "Risico"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Nasihat", w: ["Nasehat", "Nashihat", "Nasiat"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Kualitas", w: ["Kwalitas", "Kualitet", "Qualitas"], c: "Bahasa", d: "easy" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Jadwal", w: ["Jadual", "Jadwaal", "Jatwal"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Aktivitas", w: ["Aktifitas", "Aktivitaz", "Aktifitaz"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Cabai", w: ["Cabe", "Cabay", "Chabai"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Ijazah", w: ["Ijasah", "Izazah", "Ijaza"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Sistem", w: ["Sistim", "Sisterm", "Systim"], c: "Bahasa", d: "easy" },
  { q: "Sinonim dari kata cerdas adalah?", a: "Pintar", w: ["Bodoh", "Malas", "Lambat"], c: "Bahasa", d: "easy" },
  { q: "Antonim dari kata panjang adalah?", a: "Pendek", w: ["Lebar", "Tinggi", "Luas"], c: "Bahasa", d: "easy" },
  { q: "Arti peribahasa \"Bagai air di daun talas\" adalah?", a: "Pendirian yang tidak tetap", w: ["Sangat rajin bekerja", "Hidup rukun", "Mudah marah"], c: "Bahasa", d: "medium" },
  { q: "Arti peribahasa \"Berat sama dipikul, ringan sama dijinjing\" adalah?", a: "Susah dan senang ditanggung bersama", w: ["Bekerja keras sendirian", "Barang berat harus dipikul", "Membagi harta warisan"], c: "Bahasa", d: "easy" },
  { q: "Arti peribahasa \"Air beriak tanda tak dalam\" adalah?", a: "Orang yang banyak bicara biasanya kurang ilmunya", w: ["Sungai yang dangkal berbahaya", "Orang pendiam itu sombong", "Air yang tenang itu jernih"], c: "Bahasa", d: "medium" },
  { q: "Ungkapan \"buah tangan\" artinya?", a: "Oleh-oleh", w: ["Hasil panen", "Pukulan", "Tanda tangan"], c: "Bahasa", d: "easy" },
  { q: "Ungkapan \"kambing hitam\" artinya?", a: "Orang yang dipersalahkan", w: ["Orang yang pemalu", "Orang yang kaya", "Hewan kurban"], c: "Bahasa", d: "easy" },
  { q: "Ungkapan \"panjang tangan\" artinya?", a: "Suka mencuri", w: ["Suka menolong", "Suka memukul", "Pandai menari"], c: "Bahasa", d: "easy" },
  { q: "Ungkapan \"besar kepala\" artinya?", a: "Sombong", w: ["Pintar", "Pusing", "Pemimpin"], c: "Bahasa", d: "easy" },
  { q: "Ungkapan \"meja hijau\" artinya?", a: "Pengadilan", w: ["Meja belajar", "Kebun", "Meja makan"], c: "Bahasa", d: "easy" },
  { q: "Ungkapan \"kabar burung\" artinya?", a: "Kabar yang belum pasti", w: ["Kabar gembira", "Surat kabar", "Kabar dari jauh"], c: "Bahasa", d: "easy" },
  { q: "Ungkapan \"anak emas\" artinya?", a: "Anak kesayangan", w: ["Anak orang kaya", "Anak yang pintar", "Anak tunggal"], c: "Bahasa", d: "easy" },

  // --- Teknologi ---
  { q: "Siapa salah satu pendiri Apple?", a: "Steve Jobs", w: ["Bill Gates", "Elon Musk", "Larry Page"], c: "Teknologi", d: "easy" },
  { q: "Siapa pendiri Facebook?", a: "Mark Zuckerberg", w: ["Jack Dorsey", "Larry Page", "Jeff Bezos"], c: "Teknologi", d: "easy" },
  { q: "Siapa pendiri Amazon?", a: "Jeff Bezos", w: ["Elon Musk", "Bill Gates", "Jack Ma"], c: "Teknologi", d: "easy" },
  { q: "Google didirikan oleh Larry Page dan?", a: "Sergey Brin", w: ["Steve Wozniak", "Paul Allen", "Jack Ma"], c: "Teknologi", d: "medium" },
  { q: "Siapa pendiri perusahaan Alibaba?", a: "Jack Ma", w: ["Pony Ma", "Lei Jun", "Zhang Yiming"], c: "Teknologi", d: "easy" },
  { q: "Sistem operasi buatan Google untuk ponsel adalah?", a: "Android", w: ["iOS", "Windows", "HarmonyOS"], c: "Teknologi", d: "easy" },
  { q: "Instagram dan WhatsApp dimiliki oleh perusahaan?", a: "Meta", w: ["Google", "ByteDance", "Microsoft"], c: "Teknologi", d: "easy" },
  { q: "YouTube dimiliki oleh perusahaan?", a: "Google", w: ["Meta", "Microsoft", "Amazon"], c: "Teknologi", d: "easy" },
  { q: "Apa kepanjangan dari CPU?", a: "Central Processing Unit", w: ["Computer Personal Unit", "Central Program Utility", "Control Processing Unit"], c: "Teknologi", d: "medium" },
  { q: "Apa kepanjangan dari RAM?", a: "Random Access Memory", w: ["Read Access Memory", "Rapid Action Memory", "Random Active Module"], c: "Teknologi", d: "medium" },
  { q: "Apa kepanjangan dari USB?", a: "Universal Serial Bus", w: ["United Serial Bus", "Universal System Bus", "Ultra Speed Bus"], c: "Teknologi", d: "medium" },
  { q: "Satu byte terdiri dari berapa bit?", a: "8", w: ["2", "4", "16"], c: "Teknologi", d: "medium" },
  { q: "Siapa salah satu pendiri Gojek?", a: "Nadiem Makarim", w: ["William Tanuwijaya", "Achmad Zaky", "Ferry Unardi"], c: "Teknologi", d: "easy" },
  { q: "Siapa salah satu pendiri Tokopedia?", a: "William Tanuwijaya", w: ["Nadiem Makarim", "Achmad Zaky", "Belva Devara"], c: "Teknologi", d: "medium" },
  { q: "Bahasa pemrograman yang logonya berupa ular adalah?", a: "Python", w: ["Java", "JavaScript", "Ruby"], c: "Teknologi", d: "easy" },
  { q: "Pada komputer Windows, tombol pintas untuk menyalin (copy) adalah?", a: "Ctrl + C", w: ["Ctrl + V", "Ctrl + X", "Ctrl + Z"], c: "Teknologi", d: "easy" },
  { q: "Pada komputer Windows, tombol pintas untuk menempel (paste) adalah?", a: "Ctrl + V", w: ["Ctrl + C", "Ctrl + P", "Ctrl + A"], c: "Teknologi", d: "easy" },
  { q: "Pada komputer Windows, tombol pintas untuk membatalkan (undo) adalah?", a: "Ctrl + Z", w: ["Ctrl + Y", "Ctrl + U", "Ctrl + X"], c: "Teknologi", d: "easy" },
  { q: "ChatGPT dikembangkan oleh perusahaan?", a: "OpenAI", w: ["Google", "Meta", "Anthropic"], c: "Teknologi", d: "easy" },
  { q: "Satelit komunikasi pertama milik Indonesia bernama?", a: "Palapa", w: ["Garuda", "Nusantara", "Merah Putih"], c: "Teknologi", d: "medium" },

  // --- Hiburan ---
  { q: "Doraemon adalah robot kucing yang datang dari abad ke?", a: "22", w: ["21", "23", "30"], c: "Hiburan", d: "medium" },
  { q: "Siapa sahabat Doraemon yang sering meminta bantuannya?", a: "Nobita", w: ["Giant", "Suneo", "Dekisugi"], c: "Hiburan", d: "easy" },
  { q: "Serial animasi Upin & Ipin berasal dari negara?", a: "Malaysia", w: ["Indonesia", "Singapura", "Brunei"], c: "Hiburan", d: "easy" },
  { q: "Siapa kapten bajak laut Topi Jerami dalam One Piece?", a: "Monkey D. Luffy", w: ["Roronoa Zoro", "Portgas D. Ace", "Naruto Uzumaki"], c: "Hiburan", d: "easy" },
  { q: "Dalam anime Naruto, Naruto bercita-cita menjadi?", a: "Hokage", w: ["Kazekage", "Raja Bajak Laut", "Hunter"], c: "Hiburan", d: "easy" },
  { q: "Pokemon berwarna kuning dengan kekuatan listrik yang terkenal adalah?", a: "Pikachu", w: ["Charmander", "Bulbasaur", "Squirtle"], c: "Hiburan", d: "easy" },
  { q: "Karakter game Mario berprofesi sebagai?", a: "Tukang ledeng", w: ["Tukang kayu", "Koki", "Polisi"], c: "Hiburan", d: "medium" },
  { q: "Game populer yang dunianya tersusun dari balok-balok kotak adalah?", a: "Minecraft", w: ["Roblox", "Fortnite", "Mobile Legends"], c: "Hiburan", d: "easy" },
  { q: "Berapa umur Shinchan dalam serial Crayon Shinchan?", a: "5 tahun", w: ["3 tahun", "7 tahun", "10 tahun"], c: "Hiburan", d: "medium" },
  { q: "Siapa penulis cerita detektif Sherlock Holmes?", a: "Arthur Conan Doyle", w: ["Agatha Christie", "Charles Dickens", "Edgar Allan Poe"], c: "Hiburan", d: "medium" },
  { q: "Siapa penulis novel Harry Potter?", a: "J.K. Rowling", w: ["J.R.R. Tolkien", "C.S. Lewis", "Roald Dahl"], c: "Hiburan", d: "easy" },
  { q: "Nama sekolah sihir dalam kisah Harry Potter adalah?", a: "Hogwarts", w: ["Durmstrang", "Narnia", "Beauxbatons"], c: "Hiburan", d: "easy" },
  { q: "Siapa vokalis grup band NOAH?", a: "Ariel", w: ["Once Mekel", "Giring", "Armand Maulana"], c: "Hiburan", d: "easy" },
  { q: "Siapa yang dijuluki Raja Dangdut?", a: "Rhoma Irama", w: ["Meggy Z", "Mansyur S.", "Didi Kempot"], c: "Hiburan", d: "easy" },
  { q: "Grup musik BTS berasal dari negara?", a: "Korea Selatan", w: ["Jepang", "Tiongkok", "Thailand"], c: "Hiburan", d: "easy" },
  { q: "Siapa sutradara film Titanic (1997)?", a: "James Cameron", w: ["Steven Spielberg", "Christopher Nolan", "George Lucas"], c: "Hiburan", d: "medium" },
  { q: "Tokoh jahat bertopeng hitam dalam film Star Wars adalah?", a: "Darth Vader", w: ["Yoda", "Obi-Wan Kenobi", "Han Solo"], c: "Hiburan", d: "easy" },
  { q: "Superhero yang bersenjatakan perisai bergambar bintang adalah?", a: "Captain America", w: ["Iron Man", "Thor", "Hulk"], c: "Hiburan", d: "easy" },
  { q: "Siapa nama asli Spider-Man?", a: "Peter Parker", w: ["Bruce Wayne", "Clark Kent", "Tony Stark"], c: "Hiburan", d: "easy" },
  { q: "Siapa nama asli Iron Man?", a: "Tony Stark", w: ["Steve Rogers", "Bruce Banner", "Peter Parker"], c: "Hiburan", d: "easy" },
  { q: "Siapa nama asli Batman?", a: "Bruce Wayne", w: ["Clark Kent", "Barry Allen", "Tony Stark"], c: "Hiburan", d: "easy" },
  { q: "Kota tempat Batman beraksi bernama?", a: "Gotham", w: ["Metropolis", "Star City", "Central City"], c: "Hiburan", d: "easy" },
  { q: "Superhero Indonesia Gundala mendapatkan kekuatan dari?", a: "Petir", w: ["Api", "Air", "Angin"], c: "Hiburan", d: "easy" },

  // --- Tambahan: Geografi ---
  { q: "Apa ibu kota Provinsi Kalimantan Selatan?", a: "Banjarbaru", w: ["Banjarmasin", "Martapura", "Palangka Raya"], c: "Geografi", d: "hard" },
  { q: "Apa ibu kota Provinsi Sulawesi Barat?", a: "Mamuju", w: ["Majene", "Polewali", "Makassar"], c: "Geografi", d: "medium" },
  { q: "Apa ibu kota Provinsi Papua Barat?", a: "Manokwari", w: ["Sorong", "Fakfak", "Jayapura"], c: "Geografi", d: "medium" },
  { q: "Ibu Kota Nusantara (IKN) dibangun di provinsi?", a: "Kalimantan Timur", w: ["Kalimantan Tengah", "Kalimantan Selatan", "Kalimantan Utara"], c: "Geografi", d: "easy" },
  { q: "Pulau dengan jumlah penduduk terbanyak di Indonesia adalah?", a: "Jawa", w: ["Sumatera", "Sulawesi", "Kalimantan"], c: "Geografi", d: "easy" },
  { q: "Pulau yang bentuknya menyerupai huruf K adalah?", a: "Sulawesi", w: ["Halmahera", "Flores", "Timor"], c: "Geografi", d: "easy" },
  { q: "Kepulauan Raja Ampat terletak di provinsi?", a: "Papua Barat Daya", w: ["Maluku", "Papua", "Maluku Utara"], c: "Geografi", d: "hard" },
  { q: "Candi Prambanan terletak di perbatasan Yogyakarta dan provinsi?", a: "Jawa Tengah", w: ["Jawa Timur", "Jawa Barat", "Banten"], c: "Geografi", d: "medium" },
  { q: "Gunung Rinjani terletak di pulau?", a: "Lombok", w: ["Sumbawa", "Bali", "Flores"], c: "Geografi", d: "easy" },
  { q: "Gunung Kerinci, gunung api tertinggi di Indonesia, terletak di pulau?", a: "Sumatera", w: ["Jawa", "Sulawesi", "Kalimantan"], c: "Geografi", d: "medium" },
  { q: "Gunung tertinggi di Pulau Jawa adalah?", a: "Gunung Semeru", w: ["Gunung Slamet", "Gunung Merapi", "Gunung Ciremai"], c: "Geografi", d: "medium" },
  { q: "Sungai terpanjang di dunia adalah?", a: "Sungai Nil", w: ["Sungai Amazon", "Sungai Yangtze", "Sungai Mississippi"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Inggris?", a: "London", w: ["Manchester", "Liverpool", "Edinburgh"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Myanmar?", a: "Naypyidaw", w: ["Yangon", "Mandalay", "Bagan"], c: "Geografi", d: "hard" },
  { q: "Apa ibu kota India?", a: "New Delhi", w: ["Mumbai", "Kolkata", "Bangalore"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Rusia?", a: "Moskow", w: ["Sankt Peterburg", "Kazan", "Novosibirsk"], c: "Geografi", d: "easy" },
  { q: "Apa ibu kota Amerika Serikat?", a: "Washington, D.C.", w: ["New York", "Los Angeles", "Chicago"], c: "Geografi", d: "easy" },
  { q: "Apa nama mata uang Filipina?", a: "Peso", w: ["Ringgit", "Baht", "Kip"], c: "Geografi", d: "easy" },
  { q: "Apa nama mata uang Uni Eropa?", a: "Euro", w: ["Pound", "Franc", "Dolar"], c: "Geografi", d: "easy" },
  { q: "Negara dengan jumlah penduduk terbanyak di dunia saat ini adalah?", a: "India", w: ["Tiongkok", "Amerika Serikat", "Indonesia"], c: "Geografi", d: "medium" },
  { q: "Benua terkecil di dunia adalah?", a: "Australia", w: ["Eropa", "Antartika", "Amerika Selatan"], c: "Geografi", d: "easy" },
  { q: "Negara manakah yang dijuluki Negeri Paman Sam?", a: "Amerika Serikat", w: ["Inggris", "Kanada", "Australia"], c: "Geografi", d: "easy" },
  { q: "Negara manakah yang dijuluki Negeri Seribu Pagoda?", a: "Myanmar", w: ["Thailand", "Kamboja", "Laos"], c: "Geografi", d: "medium" },
  { q: "Kota manakah yang dijuluki Kota Apel?", a: "Malang", w: ["Batu", "Bogor", "Garut"], c: "Geografi", d: "easy" },

  // --- Tambahan: Sejarah ---
  { q: "Kerajaan Hindu tertua di Pulau Jawa adalah?", a: "Tarumanegara", w: ["Majapahit", "Mataram Kuno", "Singasari"], c: "Sejarah", d: "medium" },
  { q: "Siapa pendiri Kerajaan Majapahit?", a: "Raden Wijaya", w: ["Hayam Wuruk", "Ken Arok", "Gajah Mada"], c: "Sejarah", d: "medium" },
  { q: "Siapa pendiri Kerajaan Singasari?", a: "Ken Arok", w: ["Raden Wijaya", "Kertanegara", "Tunggul Ametung"], c: "Sejarah", d: "medium" },
  { q: "Kerajaan Islam pertama di Indonesia adalah?", a: "Samudera Pasai", w: ["Demak", "Aceh Darussalam", "Banten"], c: "Sejarah", d: "easy" },
  { q: "Pahlawan nasional yang memimpin Perang Jawa (1825–1830) adalah?", a: "Pangeran Diponegoro", w: ["Tuanku Imam Bonjol", "Sultan Hasanuddin", "Pattimura"], c: "Sejarah", d: "easy" },
  { q: "Pertempuran 10 November 1945 terjadi di kota?", a: "Surabaya", w: ["Semarang", "Bandung", "Ambarawa"], c: "Sejarah", d: "easy" },
  { q: "Tokoh yang terkenal dengan pekik 'Merdeka atau Mati' di Surabaya adalah?", a: "Bung Tomo", w: ["Bung Hatta", "Bung Karno", "Bung Sjahrir"], c: "Sejarah", d: "easy" },
  { q: "Jenderal besar yang terkenal dengan taktik perang gerilya adalah?", a: "Jenderal Sudirman", w: ["Jenderal A.H. Nasution", "Jenderal Ahmad Yani", "Jenderal Gatot Soebroto"], c: "Sejarah", d: "easy" },
  { q: "Kumpulan surat R.A. Kartini dibukukan dengan judul?", a: "Habis Gelap Terbitlah Terang", w: ["Di Bawah Bendera Revolusi", "Indonesia Menggugat", "Sarinah"], c: "Sejarah", d: "medium" },
  { q: "BPUPKI dibentuk pada masa penjajahan?", a: "Jepang", w: ["Belanda", "Inggris", "Portugis"], c: "Sejarah", d: "easy" },
  { q: "Siapa ketua BPUPKI?", a: "Radjiman Wedyodiningrat", w: ["Soekarno", "Mohammad Hatta", "Soepomo"], c: "Sejarah", d: "hard" },
  { q: "Siapa ketua PPKI?", a: "Soekarno", w: ["Mohammad Hatta", "Radjiman Wedyodiningrat", "Ahmad Soebardjo"], c: "Sejarah", d: "medium" },
  { q: "Pengibar Bendera Merah Putih saat proklamasi 17 Agustus 1945 adalah Latief Hendraningrat dan?", a: "Suhud", w: ["Sayuti Melik", "Sukarni", "Wikana"], c: "Sejarah", d: "hard" },
  { q: "Perjanjian yang membuat wilayah Republik Indonesia hanya tinggal Jawa Tengah, Yogyakarta, dan sebagian Sumatera adalah?", a: "Perjanjian Renville", w: ["Perjanjian Linggarjati", "Perjanjian Roem-Royen", "Perjanjian Giyanti"], c: "Sejarah", d: "hard" },
  { q: "Konferensi Meja Bundar (KMB) tahun 1949 diadakan di kota?", a: "Den Haag", w: ["Amsterdam", "Jakarta", "Paris"], c: "Sejarah", d: "medium" },
  { q: "Ibu kota Republik Indonesia sempat dipindahkan ke Yogyakarta pada tahun?", a: "1946", w: ["1945", "1948", "1950"], c: "Sejarah", d: "medium" },
  { q: "Bangsa Eropa pertama yang datang ke Indonesia adalah?", a: "Portugis", w: ["Belanda", "Spanyol", "Inggris"], c: "Sejarah", d: "medium" },
  { q: "Kebijakan tanam paksa pada masa penjajahan Belanda disebut?", a: "Cultuurstelsel", w: ["Politik Etis", "Kerja Rodi", "Romusha"], c: "Sejarah", d: "medium" },
  { q: "Kerja paksa pada masa pendudukan Jepang disebut?", a: "Romusha", w: ["Kerja Rodi", "Cultuurstelsel", "Heiho"], c: "Sejarah", d: "easy" },
  { q: "Tokoh yang dijuluki Bapak Koperasi Indonesia adalah?", a: "Mohammad Hatta", w: ["Soekarno", "Ki Hajar Dewantara", "Sutan Sjahrir"], c: "Sejarah", d: "easy" },
  { q: "Era pemerintahan Presiden Soeharto dikenal dengan sebutan?", a: "Orde Baru", w: ["Orde Lama", "Reformasi", "Demokrasi Terpimpin"], c: "Sejarah", d: "easy" },
  { q: "Era Reformasi di Indonesia dimulai pada tahun?", a: "1998", w: ["1996", "1999", "2001"], c: "Sejarah", d: "easy" },
  { q: "Tsunami dahsyat yang melanda Aceh terjadi pada tahun?", a: "2004", w: ["2002", "2006", "2009"], c: "Sejarah", d: "easy" },
  { q: "Timor Timur resmi berpisah dari Indonesia melalui jajak pendapat pada tahun?", a: "1999", w: ["1998", "2002", "1975"], c: "Sejarah", d: "medium" },
  { q: "Tokoh yang memimpin gerakan kemerdekaan India dengan cara tanpa kekerasan adalah?", a: "Mahatma Gandhi", w: ["Jawaharlal Nehru", "Indira Gandhi", "Nelson Mandela"], c: "Sejarah", d: "easy" },
  { q: "Tembok Berlin runtuh pada tahun?", a: "1989", w: ["1991", "1985", "1961"], c: "Sejarah", d: "medium" },
  { q: "Kapal Titanic tenggelam pada tahun?", a: "1912", w: ["1905", "1920", "1898"], c: "Sejarah", d: "medium" },
  { q: "Perang Dunia I dimulai pada tahun?", a: "1914", w: ["1918", "1939", "1905"], c: "Sejarah", d: "medium" },

  // --- Tambahan: Kewarganegaraan ---
  { q: "Apa bunyi sila pertama Pancasila?", a: "Ketuhanan Yang Maha Esa", w: ["Kemanusiaan yang adil dan beradab", "Persatuan Indonesia", "Keadilan sosial bagi seluruh rakyat Indonesia"], c: "Kewarganegaraan", d: "easy" },
  { q: "Apa bunyi sila kelima Pancasila?", a: "Keadilan sosial bagi seluruh rakyat Indonesia", w: ["Persatuan Indonesia", "Ketuhanan Yang Maha Esa", "Kemanusiaan yang adil dan beradab"], c: "Kewarganegaraan", d: "easy" },
  { q: "Dasar negara Republik Indonesia adalah?", a: "Pancasila", w: ["UUD 1945", "Bhinneka Tunggal Ika", "Sumpah Pemuda"], c: "Kewarganegaraan", d: "easy" },
  { q: "Semboyan Bhinneka Tunggal Ika berasal dari kitab?", a: "Sutasoma", w: ["Negarakertagama", "Arjunawiwaha", "Pararaton"], c: "Kewarganegaraan", d: "medium" },
  { q: "Kitab Sutasoma dikarang oleh?", a: "Mpu Tantular", w: ["Mpu Prapanca", "Mpu Kanwa", "Mpu Sedah"], c: "Kewarganegaraan", d: "medium" },
  { q: "Lembaga yang berwenang menguji undang-undang terhadap UUD 1945 adalah?", a: "Mahkamah Konstitusi", w: ["Mahkamah Agung", "Komisi Yudisial", "DPR"], c: "Kewarganegaraan", d: "medium" },
  { q: "Warga negara Indonesia mendapat hak pilih dalam pemilu mulai usia?", a: "17 tahun", w: ["15 tahun", "18 tahun", "21 tahun"], c: "Kewarganegaraan", d: "easy" },
  { q: "Bendera negara Indonesia disebut?", a: "Sang Saka Merah Putih", w: ["Sang Dwiwarna Jaya", "Merah Darah", "Pusaka Nusantara"], c: "Kewarganegaraan", d: "easy" },
  { q: "Pemimpin daerah tingkat provinsi disebut?", a: "Gubernur", w: ["Bupati", "Wali kota", "Camat"], c: "Kewarganegaraan", d: "easy" },
  { q: "Pemimpin daerah tingkat kabupaten disebut?", a: "Bupati", w: ["Gubernur", "Wali kota", "Lurah"], c: "Kewarganegaraan", d: "easy" },

  // --- Tambahan: Sains ---
  { q: "Planet terkecil di Tata Surya adalah?", a: "Merkurius", w: ["Mars", "Venus", "Pluto"], c: "Sains", d: "medium" },
  { q: "Galaksi tempat Tata Surya kita berada adalah?", a: "Bima Sakti", w: ["Andromeda", "Triangulum", "Magellan"], c: "Sains", d: "easy" },
  { q: "Peristiwa Bulan menutupi Matahari sehingga Bumi menjadi gelap disebut?", a: "Gerhana matahari", w: ["Gerhana bulan", "Komet", "Meteor"], c: "Sains", d: "easy" },
  { q: "Apa simbol kimia untuk natrium?", a: "Na", w: ["N", "Nt", "So"], c: "Sains", d: "medium" },
  { q: "Apa simbol kimia untuk tembaga?", a: "Cu", w: ["Tm", "Co", "Ca"], c: "Sains", d: "medium" },
  { q: "Logam yang berwujud cair pada suhu ruang adalah?", a: "Raksa", w: ["Timah", "Aluminium", "Seng"], c: "Sains", d: "medium" },
  { q: "Perubahan wujud dari padat menjadi gas disebut?", a: "Menyublim", w: ["Mencair", "Menguap", "Mengembun"], c: "Sains", d: "medium" },
  { q: "Perubahan wujud dari gas menjadi cair disebut?", a: "Mengembun", w: ["Menguap", "Membeku", "Menyublim"], c: "Sains", d: "easy" },
  { q: "Organ tubuh terbesar pada manusia adalah?", a: "Kulit", w: ["Hati", "Paru-paru", "Usus"], c: "Sains", d: "medium" },
  { q: "Bagian sel yang disebut sebagai pusat energi (pembangkit tenaga) adalah?", a: "Mitokondria", w: ["Nukleus", "Ribosom", "Vakuola"], c: "Sains", d: "medium" },
  { q: "Sel darah putih disebut juga?", a: "Leukosit", w: ["Eritrosit", "Trombosit", "Plasma"], c: "Sains", d: "medium" },
  { q: "Pembuluh darah yang membawa darah dari jantung ke seluruh tubuh adalah?", a: "Arteri", w: ["Vena", "Kapiler", "Aorta paru"], c: "Sains", d: "medium" },
  { q: "Penyakit yang disebabkan oleh nyamuk Aedes aegypti adalah?", a: "Demam berdarah", w: ["Malaria", "Tifus", "TBC"], c: "Sains", d: "easy" },
  { q: "Penyakit malaria ditularkan melalui gigitan nyamuk?", a: "Anopheles", w: ["Aedes aegypti", "Culex", "Mansonia"], c: "Sains", d: "medium" },
  { q: "Hewan yang aktif mencari makan pada malam hari disebut hewan?", a: "Nokturnal", w: ["Diurnal", "Herbivora", "Amfibi"], c: "Sains", d: "easy" },
  { q: "Hewan pemakan daging disebut?", a: "Karnivora", w: ["Herbivora", "Omnivora", "Insektivora"], c: "Sains", d: "easy" },
  { q: "Perubahan bentuk tubuh hewan dari telur hingga dewasa, seperti pada kupu-kupu, disebut?", a: "Metamorfosis", w: ["Mimikri", "Regenerasi", "Hibernasi"], c: "Sains", d: "easy" },
  { q: "Kemampuan bunglon mengubah warna kulit untuk melindungi diri disebut?", a: "Mimikri", w: ["Autotomi", "Metamorfosis", "Ekolokasi"], c: "Sains", d: "medium" },
  { q: "Kemampuan cicak memutuskan ekornya untuk melindungi diri disebut?", a: "Autotomi", w: ["Mimikri", "Regenerasi", "Kamuflase"], c: "Sains", d: "medium" },
  { q: "Bunga terbesar di dunia yang tumbuh di Indonesia adalah?", a: "Rafflesia arnoldii", w: ["Bunga bangkai (Amorphophallus)", "Anggrek hitam", "Teratai raksasa"], c: "Sains", d: "medium" },
  { q: "Hewan yang dapat hidup di darat dan di air disebut?", a: "Amfibi", w: ["Reptil", "Mamalia", "Unggas"], c: "Sains", d: "easy" },
  { q: "Apa satuan daya listrik?", a: "Watt", w: ["Volt", "Ampere", "Joule"], c: "Sains", d: "easy" },
  { q: "Apa satuan frekuensi?", a: "Hertz", w: ["Desibel", "Watt", "Newton"], c: "Sains", d: "medium" },
  { q: "Siapa penemu bola lampu pijar yang terkenal?", a: "Thomas Alva Edison", w: ["Nikola Tesla", "Michael Faraday", "James Watt"], c: "Sains", d: "easy" },
  { q: "Ilmuwan yang mengemukakan teori evolusi melalui seleksi alam adalah?", a: "Charles Darwin", w: ["Gregor Mendel", "Louis Pasteur", "Isaac Newton"], c: "Sains", d: "easy" },
  { q: "Siapa yang dikenal sebagai Bapak Genetika?", a: "Gregor Mendel", w: ["Charles Darwin", "Robert Hooke", "Louis Pasteur"], c: "Sains", d: "medium" },
  { q: "Lapisan atmosfer yang melindungi Bumi dari sinar ultraviolet adalah lapisan?", a: "Ozon", w: ["Karbon", "Nitrogen", "Hidrogen"], c: "Sains", d: "easy" },
  { q: "Alat untuk melihat benda-benda yang sangat kecil adalah?", a: "Mikroskop", w: ["Teleskop", "Periskop", "Stetoskop"], c: "Sains", d: "easy" },
  { q: "Alat yang digunakan dokter untuk mendengar detak jantung adalah?", a: "Stetoskop", w: ["Termometer", "Tensimeter", "Mikroskop"], c: "Sains", d: "easy" },

  // --- Tambahan: Matematika ---
  { q: "Berapa hasil dari 8 × 7 + 4?", a: "60", w: ["88", "56", "64"], c: "Matematika", d: "easy" },
  { q: "Berapa hasil dari 125 ÷ 5?", a: "25", w: ["20", "30", "15"], c: "Matematika", d: "easy" },
  { q: "Berapa hasil dari 13 × 11?", a: "143", w: ["133", "153", "131"], c: "Matematika", d: "medium" },
  { q: "Berapa hasil dari 1000 − 357?", a: "643", w: ["653", "743", "633"], c: "Matematika", d: "easy" },
  { q: "Berapa hasil dari 3 pangkat 4?", a: "81", w: ["12", "64", "27"], c: "Matematika", d: "easy" },
  { q: "Berapa akar kuadrat dari 225?", a: "15", w: ["25", "14", "16"], c: "Matematika", d: "medium" },
  { q: "Berapa akar pangkat tiga dari 27?", a: "3", w: ["9", "6", "4"], c: "Matematika", d: "easy" },
  { q: "Berapa 10% dari 350?", a: "35", w: ["3,5", "30", "45"], c: "Matematika", d: "easy" },
  { q: "Luas persegi panjang dengan panjang 8 cm dan lebar 5 cm adalah?", a: "40 cm²", w: ["26 cm²", "13 cm²", "45 cm²"], c: "Matematika", d: "easy" },
  { q: "Keliling persegi panjang dengan panjang 10 cm dan lebar 4 cm adalah?", a: "28 cm", w: ["40 cm", "14 cm", "24 cm"], c: "Matematika", d: "easy" },
  { q: "Luas segitiga dengan alas 10 cm dan tinggi 6 cm adalah?", a: "30 cm²", w: ["60 cm²", "16 cm²", "36 cm²"], c: "Matematika", d: "medium" },
  { q: "Volume kubus dengan rusuk 3 cm adalah?", a: "27 cm³", w: ["9 cm³", "18 cm³", "36 cm³"], c: "Matematika", d: "medium" },
  { q: "Bangun ruang yang memiliki 6 sisi berbentuk persegi adalah?", a: "Kubus", w: ["Balok", "Prisma", "Limas"], c: "Matematika", d: "easy" },
  { q: "Jumlah besar sudut dalam segi empat adalah?", a: "360°", w: ["180°", "270°", "540°"], c: "Matematika", d: "medium" },
  { q: "Angka Romawi M bernilai?", a: "1000", w: ["500", "100", "5000"], c: "Matematika", d: "easy" },
  { q: "Angka Romawi D bernilai?", a: "500", w: ["50", "1000", "5000"], c: "Matematika", d: "medium" },
  { q: "Angka 2026 jika ditulis dengan angka Romawi adalah?", a: "MMXXVI", w: ["MMXVI", "MMXXIV", "MCMXXVI"], c: "Matematika", d: "hard" },
  { q: "KPK dari 4 dan 6 adalah?", a: "12", w: ["24", "2", "10"], c: "Matematika", d: "medium" },
  { q: "FPB dari 12 dan 18 adalah?", a: "6", w: ["3", "36", "12"], c: "Matematika", d: "medium" },
  { q: "Satu kuintal sama dengan berapa kilogram?", a: "100", w: ["10", "1000", "50"], c: "Matematika", d: "medium" },

  // --- Tambahan: Olahraga ---
  { q: "Berapa jumlah pemain satu tim futsal di lapangan?", a: "5", w: ["6", "7", "11"], c: "Olahraga", d: "easy" },
  { q: "Berapa jumlah pemain satu tim sepak takraw di lapangan?", a: "3", w: ["2", "4", "5"], c: "Olahraga", d: "medium" },
  { q: "Olahraga yang menggunakan kok (shuttlecock) adalah?", a: "Bulu tangkis", w: ["Tenis", "Squash", "Tenis meja"], c: "Olahraga", d: "easy" },
  { q: "Olahraga bela diri asli Indonesia adalah?", a: "Pencak silat", w: ["Karate", "Taekwondo", "Kung fu"], c: "Olahraga", d: "easy" },
  { q: "Karate adalah olahraga bela diri yang berasal dari negara?", a: "Jepang", w: ["Korea Selatan", "Tiongkok", "Thailand"], c: "Olahraga", d: "easy" },
  { q: "Taekwondo adalah olahraga bela diri yang berasal dari negara?", a: "Korea Selatan", w: ["Jepang", "Tiongkok", "Vietnam"], c: "Olahraga", d: "easy" },
  { q: "Lionel Messi berasal dari negara?", a: "Argentina", w: ["Spanyol", "Brasil", "Uruguay"], c: "Olahraga", d: "easy" },
  { q: "Penghargaan untuk pemain sepak bola terbaik dunia setiap tahun disebut?", a: "Ballon d'Or", w: ["Golden Boot", "Golden Glove", "Piala Eropa"], c: "Olahraga", d: "medium" },
  { q: "Negara mana yang menjuarai Piala Dunia FIFA 2014?", a: "Jerman", w: ["Argentina", "Brasil", "Spanyol"], c: "Olahraga", d: "medium" },
  { q: "Olimpiade modern pertama diadakan pada tahun 1896 di kota?", a: "Athena", w: ["Paris", "London", "Roma"], c: "Olahraga", d: "medium" },
  { q: "Olimpiade diselenggarakan setiap berapa tahun sekali?", a: "4 tahun", w: ["2 tahun", "3 tahun", "5 tahun"], c: "Olahraga", d: "easy" },
  { q: "Asian Games 2018 diselenggarakan di Jakarta dan kota?", a: "Palembang", w: ["Bandung", "Surabaya", "Medan"], c: "Olahraga", d: "easy" },
  { q: "Pebalap Indonesia pertama yang tampil di ajang Formula 1 adalah?", a: "Rio Haryanto", w: ["Sean Gelael", "Ananda Mikola", "Doni Tata"], c: "Olahraga", d: "medium" },
  { q: "Lalu Muhammad Zohri adalah atlet Indonesia cabang?", a: "Atletik (lari cepat)", w: ["Renang", "Angkat besi", "Panahan"], c: "Olahraga", d: "medium" },
  { q: "Eko Yuli Irawan adalah atlet Indonesia cabang?", a: "Angkat besi", w: ["Bulu tangkis", "Panjat tebing", "Pencak silat"], c: "Olahraga", d: "medium" },
  { q: "Veddriq Leonardo meraih medali emas Olimpiade Paris 2024 untuk Indonesia di cabang?", a: "Panjat tebing", w: ["Angkat besi", "Panahan", "Bulu tangkis"], c: "Olahraga", d: "hard" },
  { q: "Dalam bola basket, tembakan dari luar garis busur bernilai berapa poin?", a: "3", w: ["2", "1", "4"], c: "Olahraga", d: "easy" },

  // --- Tambahan: Budaya ---
  { q: "Tari Serimpi berasal dari daerah?", a: "Jawa Tengah", w: ["Bali", "Jawa Barat", "Sumatera Barat"], c: "Budaya", d: "medium" },
  { q: "Tari Legong berasal dari daerah?", a: "Bali", w: ["Jawa Timur", "Lombok", "Jawa Tengah"], c: "Budaya", d: "easy" },
  { q: "Tari Gandrung berasal dari daerah?", a: "Banyuwangi", w: ["Ponorogo", "Madura", "Cirebon"], c: "Budaya", d: "medium" },
  { q: "Tari Maengket berasal dari provinsi?", a: "Sulawesi Utara", w: ["Sulawesi Selatan", "Maluku", "Gorontalo"], c: "Budaya", d: "hard" },
  { q: "Tari Kipas Pakarena berasal dari provinsi?", a: "Sulawesi Selatan", w: ["Sulawesi Utara", "Kalimantan Timur", "Bali"], c: "Budaya", d: "medium" },
  { q: "Alat musik gamelan terutama berasal dari pulau?", a: "Jawa dan Bali", w: ["Sumatera", "Sulawesi", "Kalimantan"], c: "Budaya", d: "easy" },
  { q: "Alat musik Sape (Sampe) berasal dari suku?", a: "Dayak", w: ["Batak", "Toraja", "Asmat"], c: "Budaya", d: "medium" },
  { q: "Alat musik Gondang berasal dari suku?", a: "Batak", w: ["Minangkabau", "Dayak", "Sunda"], c: "Budaya", d: "medium" },
  { q: "Suku Asmat yang terkenal dengan seni ukir kayunya berasal dari?", a: "Papua", w: ["Kalimantan", "Maluku", "Sulawesi"], c: "Budaya", d: "easy" },
  { q: "Rumah adat Baileo berasal dari provinsi?", a: "Maluku", w: ["Papua", "Sulawesi Utara", "Nusa Tenggara Timur"], c: "Budaya", d: "hard" },
  { q: "Rumah Kebaya adalah rumah adat suku?", a: "Betawi", w: ["Sunda", "Jawa", "Melayu"], c: "Budaya", d: "medium" },
  { q: "Rumah Krong Bade adalah rumah adat dari daerah?", a: "Aceh", w: ["Riau", "Jambi", "Sumatera Utara"], c: "Budaya", d: "hard" },
  { q: "Pakaian adat Ulee Balang berasal dari daerah?", a: "Aceh", w: ["Sumatera Barat", "Riau", "Bengkulu"], c: "Budaya", d: "hard" },
  { q: "Pakaian adat Bundo Kanduang berasal dari suku?", a: "Minangkabau", w: ["Batak", "Melayu", "Betawi"], c: "Budaya", d: "medium" },
  { q: "Senjata tradisional Clurit identik dengan suku?", a: "Madura", w: ["Betawi", "Bugis", "Dayak"], c: "Budaya", d: "easy" },
  { q: "Seudati adalah tarian tradisional dari daerah?", a: "Aceh", w: ["Riau", "Sumatera Barat", "Bali"], c: "Budaya", d: "medium" },
  { q: "Seblak adalah makanan khas daerah?", a: "Jawa Barat", w: ["Jawa Tengah", "Jakarta", "Jawa Timur"], c: "Budaya", d: "easy" },
  { q: "Ayam taliwang adalah makanan khas daerah?", a: "Lombok", w: ["Bali", "Makassar", "Manado"], c: "Budaya", d: "medium" },
  { q: "Kue Bingka adalah kue khas dari daerah?", a: "Kalimantan Selatan", w: ["Sumatera Barat", "Jawa Tengah", "Papua"], c: "Budaya", d: "hard" },
  { q: "Wayang yang terbuat dari kulit dan dimainkan di balik layar disebut?", a: "Wayang kulit", w: ["Wayang golek", "Wayang orang", "Wayang klitik"], c: "Budaya", d: "easy" },
  { q: "Wayang golek yang terbuat dari kayu terkenal berasal dari daerah?", a: "Jawa Barat", w: ["Jawa Timur", "Bali", "Sumatera"], c: "Budaya", d: "easy" },
  { q: "Lagu Anging Mammiri berasal dari daerah?", a: "Sulawesi Selatan", w: ["Sulawesi Utara", "Maluku", "Kalimantan Timur"], c: "Budaya", d: "medium" },
  { q: "Lagu Soleram berasal dari daerah?", a: "Riau", w: ["Aceh", "Jambi", "Bengkulu"], c: "Budaya", d: "medium" },
  { q: "Lagu Butet berasal dari daerah?", a: "Sumatera Utara", w: ["Sumatera Barat", "Riau", "Aceh"], c: "Budaya", d: "medium" },
  { q: "Lagu Apuse berasal dari daerah?", a: "Papua", w: ["Maluku", "Nusa Tenggara Timur", "Sulawesi Utara"], c: "Budaya", d: "medium" },

  // --- Tambahan: Bahasa ---
  { q: "Manakah penulisan kata baku yang benar?", a: "Analisis", w: ["Analisa", "Analisys", "Analise"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Karier", w: ["Karir", "Karrier", "Kariir"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Objek", w: ["Obyek", "Objeck", "Obeyek"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Hakikat", w: ["Hakekat", "Hakiket", "Hakikad"], c: "Bahasa", d: "medium" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Kreatif", w: ["Kreativ", "Kretif", "Kriatif"], c: "Bahasa", d: "easy" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Zaman", w: ["Jaman", "Zamman", "Djaman"], c: "Bahasa", d: "easy" },
  { q: "Manakah penulisan kata baku yang benar?", a: "Rezeki", w: ["Rejeki", "Rizki", "Rejeky"], c: "Bahasa", d: "medium" },
  { q: "Sinonim dari kata bahagia adalah?", a: "Gembira", w: ["Sedih", "Marah", "Lelah"], c: "Bahasa", d: "easy" },
  { q: "Sinonim dari kata indah adalah?", a: "Elok", w: ["Buruk", "Kotor", "Rusak"], c: "Bahasa", d: "easy" },
  { q: "Antonim dari kata rajin adalah?", a: "Malas", w: ["Tekun", "Giat", "Ulet"], c: "Bahasa", d: "easy" },
  { q: "Antonim dari kata kaya adalah?", a: "Miskin", w: ["Mewah", "Makmur", "Hemat"], c: "Bahasa", d: "easy" },
  { q: "Arti peribahasa \"Tong kosong nyaring bunyinya\" adalah?", a: "Orang yang sedikit ilmunya biasanya banyak bicara", w: ["Orang pintar suka menolong", "Barang murah mudah rusak", "Orang sabar disayang Tuhan"], c: "Bahasa", d: "medium" },
  { q: "Arti peribahasa \"Sedikit demi sedikit, lama-lama menjadi bukit\" adalah?", a: "Hasil dikumpulkan sedikit-sedikit lama-lama menjadi banyak", w: ["Mendaki bukit harus perlahan", "Pekerjaan berat harus dibagi", "Jangan mudah menyerah saat gagal"], c: "Bahasa", d: "easy" },
  { q: "Ungkapan \"tangan kanan\" artinya?", a: "Orang kepercayaan", w: ["Orang yang pelit", "Orang yang kidal", "Orang yang suka memukul"], c: "Bahasa", d: "easy" },
  { q: "Ungkapan \"keras kepala\" artinya?", a: "Tidak mau menuruti nasihat", w: ["Pintar sekali", "Sering sakit kepala", "Pemberani"], c: "Bahasa", d: "easy" },
  { q: "Ungkapan \"ringan tangan\" artinya?", a: "Suka menolong", w: ["Suka mencuri", "Malas bekerja", "Mudah lelah"], c: "Bahasa", d: "medium" },

  // --- Tambahan: Teknologi ---
  { q: "Apa kepanjangan dari HTML?", a: "HyperText Markup Language", w: ["High Tech Modern Language", "HyperText Machine Logic", "Home Tool Markup Language"], c: "Teknologi", d: "medium" },
  { q: "Apa kepanjangan dari Wi-Fi yang umum dikenal?", a: "Wireless Fidelity", w: ["Wide Fiber", "Wireless Finder", "Web Fidelity"], c: "Teknologi", d: "medium" },
  { q: "Apa kepanjangan dari PDF?", a: "Portable Document Format", w: ["Printed Data File", "Personal Document File", "Public Data Format"], c: "Teknologi", d: "medium" },
  { q: "Satu kilobyte (KB) umumnya setara dengan berapa byte?", a: "1024", w: ["1000", "100", "512"], c: "Teknologi", d: "medium" },
  { q: "Sistem operasi buatan Apple untuk iPhone adalah?", a: "iOS", w: ["Android", "macOS", "Windows"], c: "Teknologi", d: "easy" },
  { q: "Siapa pendiri perusahaan Tesla dan SpaceX yang terkenal?", a: "Elon Musk", w: ["Jeff Bezos", "Bill Gates", "Mark Zuckerberg"], c: "Teknologi", d: "easy" },
  { q: "Perangkat keras yang berfungsi sebagai otak komputer adalah?", a: "CPU (prosesor)", w: ["Monitor", "Keyboard", "Speaker"], c: "Teknologi", d: "easy" },
  { q: "Pada komputer Windows, tombol pintas untuk memotong (cut) adalah?", a: "Ctrl + X", w: ["Ctrl + C", "Ctrl + V", "Ctrl + Z"], c: "Teknologi", d: "easy" },
  { q: "Pada komputer Windows, tombol pintas untuk menyimpan (save) adalah?", a: "Ctrl + S", w: ["Ctrl + P", "Ctrl + A", "Ctrl + N"], c: "Teknologi", d: "easy" },
  { q: "Pada komputer Windows, tombol pintas untuk memilih semua (select all) adalah?", a: "Ctrl + A", w: ["Ctrl + S", "Ctrl + E", "Ctrl + L"], c: "Teknologi", d: "easy" },
  { q: "Pesan tidak diinginkan yang dikirim secara massal lewat email disebut?", a: "Spam", w: ["Cookie", "Bug", "Cache"], c: "Teknologi", d: "easy" },
  { q: "Kesalahan pada program komputer biasa disebut?", a: "Bug", w: ["Spam", "Patch", "Plugin"], c: "Teknologi", d: "easy" },
  { q: "Pesawat N-250 Gatotkaca dirancang di bawah pimpinan?", a: "B.J. Habibie", w: ["Soekarno", "Nadiem Makarim", "Sri Mulyani"], c: "Teknologi", d: "medium" },
  { q: "Siapa salah satu pendiri Bukalapak?", a: "Achmad Zaky", w: ["Nadiem Makarim", "William Tanuwijaya", "Ferry Unardi"], c: "Teknologi", d: "medium" },
  { q: "Siapa salah satu pendiri Traveloka?", a: "Ferry Unardi", w: ["Achmad Zaky", "Nadiem Makarim", "Belva Devara"], c: "Teknologi", d: "hard" },

  // --- Tambahan: Hiburan ---
  { q: "Film animasi Disney yang menampilkan Ratu Elsa dan kekuatan esnya adalah?", a: "Frozen", w: ["Moana", "Tangled", "Encanto"], c: "Hiburan", d: "easy" },
  { q: "Film animasi Pixar tentang mainan koboi bernama Woody adalah?", a: "Toy Story", w: ["Cars", "Up", "Coco"], c: "Hiburan", d: "easy" },
  { q: "Singa muda bernama Simba adalah tokoh utama dalam film?", a: "The Lion King", w: ["Madagascar", "Zootopia", "Kung Fu Panda"], c: "Hiburan", d: "easy" },
  { q: "Raksasa hijau yang tinggal di rawa dalam film animasi DreamWorks adalah?", a: "Shrek", w: ["Hulk", "Grinch", "Yoda"], c: "Hiburan", d: "easy" },
  { q: "Superhero dari Wakanda adalah?", a: "Black Panther", w: ["Doctor Strange", "Ant-Man", "Hawkeye"], c: "Hiburan", d: "easy" },
  { q: "Palu sakti Mjolnir adalah senjata milik superhero?", a: "Thor", w: ["Hulk", "Loki", "Captain Marvel"], c: "Hiburan", d: "easy" },
  { q: "Superhero yang berasal dari planet Krypton adalah?", a: "Superman", w: ["Batman", "Flash", "Aquaman"], c: "Hiburan", d: "easy" },
  { q: "Tokoh utama anime Dragon Ball adalah?", a: "Son Goku", w: ["Vegeta", "Naruto", "Luffy"], c: "Hiburan", d: "easy" },
  { q: "Detektif cilik dalam anime Detective Conan bernama asli?", a: "Shinichi Kudo", w: ["Kogoro Mouri", "Heiji Hattori", "Kaito Kid"], c: "Hiburan", d: "medium" },
  { q: "Boneka tokoh anak Indonesia yang populer sejak tahun 1980-an adalah?", a: "Si Unyil", w: ["Si Doel", "Si Kabayan", "Si Buta"], c: "Hiburan", d: "easy" },
  { q: "Grup musik K-pop wanita yang beranggotakan Jisoo, Jennie, Rosé, dan Lisa adalah?", a: "BLACKPINK", w: ["TWICE", "Red Velvet", "NewJeans"], c: "Hiburan", d: "easy" },
  { q: "Lagu Bukti (2017) dipopulerkan oleh penyanyi?", a: "Virgoun", w: ["Ari Lasso", "Afgan", "Judika"], c: "Hiburan", d: "medium" },
  { q: "Lagu Laskar Pelangi dipopulerkan oleh grup band?", a: "Nidji", w: ["Peterpan", "Sheila on 7", "Ungu"], c: "Hiburan", d: "medium" },
  { q: "Grup band asal Yogyakarta yang terkenal dengan lagu Dan dan Sephia adalah?", a: "Sheila on 7", w: ["Dewa 19", "Padi", "Slank"], c: "Hiburan", d: "medium" },
  { q: "Karakter game berbentuk landak biru yang bisa berlari sangat cepat adalah?", a: "Sonic", w: ["Mario", "Pac-Man", "Kirby"], c: "Hiburan", d: "easy" },
  { q: "Game mobile MOBA populer yang banyak dimainkan di Indonesia dengan singkatan MLBB adalah?", a: "Mobile Legends: Bang Bang", w: ["Arena of Valor", "League of Legends", "Free Fire"], c: "Hiburan", d: "easy" }
];
